<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Log\Grid\LastActions $block */

?>

<span style="float:right;">
    <a title="<?php /* @noEscape */ echo $block->getTip(); ?>"
       id="grid_help_icon_open_<?php /* @noEscape */ echo $block->getEntityId(); ?>"
       href="javascript:void(0);"
       onclick="<?php /* @noEscape */ echo $block->getViewHelpHandler(); ?>('<?php /* @noEscape */ echo $block->getEntityId(); ?>', '<?php /* @noEscape */ echo $block->getEncodedRows(); ?>', <?php /* @noEscape */ echo $block->getHideViewLogLink(); ?>)">
        <img src="<?php /* @noEscape */ echo $block->getIconSrc(); ?>" alt="<?php /* @noEscape */ echo $block->getTip(); ?>" />
    </a>
    <a title="<?php /* @noEscape */ echo $block->getTip(); ?>"
       id="grid_help_icon_close_<?php /* @noEscape */ echo $block->getEntityId(); ?>"
       style="display: none;"
       href="javascript:void(0);"
       onclick="<?php /* @noEscape */ echo $block->getCloseHelpHandler(); ?>('<?php /* @noEscape */ echo $block->getEntityId(); ?>')">
        <img src="<?php /* @noEscape */ echo $block->getIconSrc(); ?>" alt="<?php /* @noEscape */ echo $block->getTip(); ?>" />
    </a>
</span>
