<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<div id="next_step_warning_popup_content" style="display: none">

    <div>
        <?php echo $block->__(
            '<b>Warning:</b> There are <span id="failed_count"></span> Product(s) of <span id="total_count"></span> which have no eBay Catalog Primary Category specified.<br/><br/>
            To add eBay Catalog Primary Categories now, click <b>Cancel</b> then choose the Edit Category Action for the Products which need them.<br/><br/>
            If you\'re not ready to add eBay Catalog Primary Categories yet or are not sure which Category to choose, click <b>Continue</b>.
            You will have a chance to add Categories later in the M2E Pro Listing Settings.'
        ); ?>
    </div>

</div>