<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Wizard\MigrationFromMagento1\Installation\Congratulation\Content $block */

?>

<div class="wizard_block">

    <p>
        <?php echo $block->__('Our congratulations! You have migrated M2E Pro data from Magento v1.x to Magento v2.x.'); ?>
    </p>

    <p>
        <?php echo $block->__('
            Enable automatic synchronization to start syncing your Magento inventory and sales with Channels.
            Click <strong>Complete</strong> to exit the Wizard.
        '); ?>
    </p>

    <p>
        <?php echo $block->getChildHtml('enable_synchronization_form'); ?>
    </p>
</div>
