<?php /** @var \Ess\M2ePro\Block\Adminhtml\Wizard\MigrationFromMagento1\Installation\Congratulation\Content $block */ ?>

<div class="wizard_block">

    <h2>
        <?php echo $block->__('Our Congratulations! You have successfully completed the Migration process.'); ?>
    </h2>

    <p>
        <?php echo $block->__('So now M2E Pro dynamic tasks run by Cron are automatically enabled and M2E Pro Interface is unblocked. Thus, you can use all available M2E Pro features for the version based on the Magento v2.x.'); ?>
    </p>
</div>