<?php /** @var \Ess\M2ePro\Block\Adminhtml\Wizard\MigrationFromMagento1\Installation\Welcome\Content $block */ ?>

<div class="wizard_block">

    <h2>
        <?php echo $block->__('Congratulations! You have successfully proceeded to M2E Pro Data migration from Magento v 1.x to Magento v 2.x.'); ?>
    </h2>

    <h3>
        <?php echo $block->__('What was changed?'); ?>
    </h3>

    <ol class="migration-notes">
        <li>
            <?php echo $block->__(
"Currently, some of the features from M2E Pro versions for Magento v 1.x. are not available in M2E Pro for Magento v 2.x. You can find the list of the temporary unavailable properties below.<br/><br/>
Please be advised that the missing features have been scheduled for development and will be added shortly."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"The eBay Listing Simple Mode functionality is no longer supported because a number of modifications were implemented in order to simplify and make work with M2E Pro more convenient. As the current configurations do not require any special skills or advanced experience, the Simple Mode is not going to be of use any longer."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"The concept of M2E Pro global settings was changed. Now, only the ability to enable/disable Channels is available in general Magento Configurations (in Stores > Settings > Configuration > Multi Channels section).<br/><br/>
Moreover, the License management options, Logs Clearing configurations, Synchronization Logs, etc. are available in M2E&nbsp;Pro menu for each Integration separately. Navigate to Configuration > Settings section of the Integration you are using to specify the settings which will best suit your needs."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"The Listing section was improved. Now, you can manage M2E Pro and 3rd party Listings as well as use the Product Search tool independently on separate pages."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"The User Interface was totally re-arranged by re-grouping the features, settings, etc.  in attempt to simplify and make it more understandable."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"M2E Pro Documentation was re-written and a separate section for M2E Pro Magento v 2.x was created along with the changes made to the Knowledge Base articles."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"Logs section was fully changed. The Logs & Events data is currently available for 3 different sections: Listing Logs & Events, Orders Logs & Events and Synchronization Logs (available in Help Center > For Developers > Synchronization Log tab)."
            ); ?>
        </li>
        <li>
            <?php echo $block->__(
"The information which could be helpful for Developers and Magento Administrators is gathered in a single section and available in the Help Center > For Developers section of the menu,  etc."
            ); ?>
        </li>
    </ol>

    <br/>

    <h3>
        <?php echo $block->__('The List of Temporary Unavailable features'); ?>
    </h3>
    <h5>
        <?php echo $block->__('Development and implementation of the features below is scheduled for Q4, 2016'); ?>
    </h5>

    <ul class="migration-notes">
        <li>
            <?php echo $block->__('ability to use Parts Compatibility options for eBay Items;'); ?>
        </li>
        <li>
            <?php echo $block->__('ability to manage eBay Categories in Sell on eBay > Configuration > Categories in Use section;'); ?>
        </li>
        <li>
            <?php echo $block->__('eBay \'Sell on another Marketplace\' feature;'); ?>
        </li>
        <li>
            <?php echo $block->__('ability to apply Amazon\'s Shipping Service feature;'); ?>
        </li>
    </ul>

    <p>
        <?php echo $block->__('In addition to, the ability to apply the Schedule settings for List/Relist actions in the Synchronization Policy is no longer supported.'); ?>
    </p>
    <p>
        <?php echo $block->__('<strong>Please note</strong>, if you currently have the Schedule settings applied, they will be reseted. Thus, the List/Relist actions could be executed anytime.'); ?>
    </p>
    <p>
        <?php echo $block->__('This option is not supported because it is less-intensively used among current M2E Pro Users.'); ?>
    </p>
    <p>
        <?php echo $block->__('The eBay Listing Simple Mode functionality is no longer supported because a number of modifications were implemented in order to simplify and make work with M2E Pro more convenient.<br> As the current configurations do not require any special skills or advanced experience, the Simple Mode is not going to be of use any longer.'); ?>
    </p>
    <p>
        <?php echo $block->__('Moreover, the Rakuten.com Integration is not planned to be supported for M2E Pro for Magento v2.x because of lack of minimum required technical base on Rakuten.com which lead to inability to properly organize the integration running.'); ?>
    </p>
    <p>
        <?php echo $block->__('Also, the ability to switch between Listings using an arrow next to the Listing Title at the top of the Listing page is no longer supported in M2E Pro for Magento v2.x. either.'); ?>
    </p>
    <p>
        <?php echo $block->__('This option in no longer helpful in M2E Pro for Magento v2.x because of the major changes made in the Interface of the Extension.'); ?>
    </p>
</div>