<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Amazon\Listing\Product\Template\ShippingTemplate $block */

?>

<div id="template_shippingTemplate_pop_up_content">
    <div>

        <?php if (!empty($block->getMessages())) : ?>
            <div id="template_shippingTemplate_error_block">
                <?php echo $block->getWarnings(); ?>
            </div>
        <?php endif; ?>

        <?php echo $block->createBlock('HelpBlock')->setData([
            'content' => $block->__(
                'The Shipping Template Policy is using to specify the Shipping Settings provided in Amazon Seller Central.<br />
                You can select the Policy from the list of already created or add a new one for your Product by pressing <strong>Add New Shipping Template Policy</strong> Button.'
            )
        ])->toHtml(); ?>

        <div id="template_shipping_grid">
        </div>

    </div>
</div>
