<style type="text/css">
    #magento_block_ebay_category_specific_item_specifics table td, #magento_block_ebay_category_specific_item_specifics table th {
        padding: 5px;
    }

    #magento_block_ebay_category_specific_item_specifics td.label, #magento_block_ebay_category_specific_item_specifics td.label {
        width: 100px;
    }
</style>

<div id="specific_main_container" style="padding: 30px 0">
    <?php echo $block->getChildHtml('specific'); ?>
</div>
