<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Category\Chooser\Tabs\Attribute $block */
?>

<div id="chooser_attributes">
    <table id="chooser_attributes_table">
        <thead>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
