<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Listing\View\Ebay\Fee\Product $block */

$feeDetailsId = uniqid('fee-details-');

$title = $block->getHelper('Data')->escapeHtml($block->__('Estimated Fee Details For Product: "%title%"', $block->getData('product_name')));
?>

<div id="<?php /* @noEscape */ echo $feeDetailsId ?>" style="display: none;">
    <?php /* @noEscape */ echo $block->getChildHtml('details'); ?>
</div>
<span>
    <?php /* @noEscape */ echo $block->getTotalFee() ?>&nbsp;<a
        href="javascript:void(0);"
        class="ebay-fee"
        onclick="EbayListingViewEbayGridObj.openFeePopUp($('<?php /* @noEscape */ echo $feeDetailsId ?>').innerHTML, '<?php /* @noEscape */ echo $title ?>');"
    ><?php /* @noEscape */ echo $block->__('details') ?></a>
</span>
