<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Inspection\Requirements $block */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label" style="width:200px;">
            <strong><?php echo $block->__('Properties'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo $block->__('Minimum / Recommended Value'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo $block->__('Current Value'); ?></strong>
        </td>
    </tr>

    <?php foreach ($block->getManager()->getChecks() as $check) { ?>
        <tr>
            <td class="label">
                <label><?php echo $check->getRenderer()->getTitle(); ?></label>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getMin(); ?>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getReal(); ?>
            </td>
        </tr>
    <?php } ?>

</table>