<table class="form-list" cellspacing="0" cellpadding="0">

    <?php if ($this->getHelper('Client\Cache')->isApcAvailable()) : ?>
        <tr>
            <td class="label">
                <label><?php echo $this->__('APC'); ?>: </label>
            </td>
            <td class="value">
                <span><?php echo $this->__('Installed'); ?></span>
                <?php if ($this->getHelper('Client\Cache')->isApcEnabled()) : ?>
                    <span class="red" style="font-weight: bold;"> (<?php echo $this->__('Enabled'); ?>)</span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>

</table>