<table class="form-list" cellspacing="0" cellpadding="0">

    <?php if ($this->getHelper('Client\Cache')->isApcAvailable()) : ?>
        <tr>
            <td class="label">
                <label><?php echo $this->__('APC'); ?>: </label>
            </td>
            <td class="value">
                <span><?php echo $this->__('Installed'); ?></span>
            </td>
        </tr>
    <?php endif; ?>

</table>