<table class="form-list" cellspacing="0" cellpadding="0">

    <?php foreach ($this->emptyTables as $table) :?>
        <tr>
            <td class="label">
                <?php echo $table?>
            </td>
            <td class="value">
                <span style="color: red">no records found</span>
            </td>
        </tr>
    <?php endforeach; ?>

    <?php foreach ($this->notInstalledTables as $table) :?>
        <tr>
            <td class="label">
                <?php echo $table?>
            </td>
            <td class="value">
                <span style="color: red">table not installed</span>
            </td>
        </tr>
    <?php endforeach; ?>

    <?php foreach ($this->crashedTables as $table) :?>
        <tr>
            <td class="label">
                <?php echo $table?>
            </td>
            <td class="value">
                <span style="color: red;">table is crashed</span>
                <a style="margin-left: 10px;" href="<?php echo $this->getUrl('*/controlPanel_inspection/repairCrashedTable', array('table_name' => $table)); ?>">Repair</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>