<?php
    /** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Inspection\Requirements $this */
?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label" style="width:200px;">
            <strong><?php echo $this->__('Properties'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo $this->__('Minimum / Recommended Value'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo $this->__('Current Value'); ?></strong>
        </td>
    </tr>

    <?php foreach($this->getManager()->getChecks() as $check) { ?>
        <tr>
            <td class="label">
                <label><?php echo $check->getRenderer()->getTitle(); ?></label>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getMin(); ?>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getReal(); ?>
            </td>
        </tr>
    <?php } ?>

</table>