<?php

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Inspection\VersionInfo $block */
?>

<table class="form-list">

    <tr>
        <td class="label">
            <label><?= __('Current Version'); ?>:</label>
        </td>
        <td class="value"><?= $block->currentVersion; ?></td>
    </tr>

    <?php if ($block->latestPublicVersion) : ?>
    <tr>
        <td class="label">
            <label><?= __('Latest Public Version'); ?>:</label>
        </td>
        <td class="value">
            <?= $block->latestPublicVersion; ?>
            <?php $releaseNotesUrl = $block
                ->getHelper('Module_Support')
                ->getDocumentationArticleUrl("help/m2/release-notes-policy")
            ?>
            <a href="<?= $releaseNotesUrl; ?>" target="_blank"><?= __('[release notes]'); ?></a>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!$block->getData('is_support_mode')) : ?>
    <tr>
        <td class="label">
            <label><?= __('History'); ?>:</label>
        </td>
        <td class="value">
            <?php $showHistoryUrl = $block->getUrl(
                '*/controlPanel_database/manageTable',
                ['table' => 'm2epro_setup']
            ); ?>
            <a target="_blank" href="<?= $showHistoryUrl; ?>"><?= __('show'); ?></a>
        </td>
    </tr>
    <?php endif; ?>

</table>
