<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Wizard\InstallationWalmart\Installation\ListingTutorial\Content $block */

?>

<div class="wizard_block">
    <h2>
        <?php echo $block->__('Congratulations! You have successfully registered your M2E Pro Extension and linked your Walmart Account to it.'); ?>
    </h2>

    <p>
        <?php echo $block->__('The next step involves creating your first M2E Pro Listing.'); ?>
    </p>

    <br/>
    <p>
        <?php echo $block->__('M2E Pro Listing is a group of Magento Products combined under specific sets of rules. <br/> These are the Products which will be offered as Walmart Items by a Seller on a particular Marketplace.'); ?>
    </p>

    <br/>
    <p>
        <?php echo $block->__('Click on <strong>Create First Listing</strong> button to proceed.'); ?>
    </p>
</div>
