<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Listing\View\Settings\Motors\View\Group\Items $block */

?>

<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
    <table class="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th" style="width: 75px;"><?php /* @noEscape */ echo $block->getItemTitle()?></th>
            <th class="data-grid-th"><?php /* @noEscape */ echo $block->__('Note')?></th>
            <th class="data-grid-th no-link" style="width: 20px;">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getGroup()->getItems() as $item) { ?>
            <tr>
                <td>
                    <?php /* @noEscape */ echo $item['id']?>
                </td>
                <td>
                    <?php /* @noEscape */ echo $item['note']?>
                </td>
                <td>
                    <a title="<?php /* @noEscape */ echo $block->__('Remove') ?>"
                       href="javascript:void(0)"
                       class="ebay-listing-view-icon ebay-listing-view-remove"
                       onclick="EbayListingViewSettingsMotorsAddGroupGridObj.removeItemFromGroup(this, <?php /* @noEscape */ echo $item['id']?>, <?php /* @noEscape */ echo $block->getGroupId() ?>)">
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
