<?php

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Listing\Product\ShowOthersListingsProductsFilter $block */

?>

<style>
    div.switcher {
        margin-bottom: 30px;
        padding: 1.5em;
    }
    div.switcher label span {
        margin-left: .5em;
    }
    div.switcher .item {
        display: inline-block;
        margin-left: 15px;
    }
    div.switcher .item:first-child {
        margin-left: initial;
    }
</style>

<div class="switcher m2epro-box-style">
    <?php foreach ($block->getAllFilters() as $filter) : ?>
        <?= $block->renderFilter($filter) ?>
    <?php endforeach; ?>
</div>

