<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Backend\Block\Widget\Button\SplitButton */
?>

<div <?php /* @noEscape */ echo $block->getAttributesHtml(); ?>>
    <?php if ($block->hasSplit()): ?>
        <button <?php /* @noEscape */ echo $block->getToggleAttributesHtml() ?> style="position: static; padding-left: 2rem;">
            <span style="position: static;
                         display: inline;
                         visibility: visible;">
                <?php /* @noEscape */ echo $block->escapeHtml($block->getLabel()); ?>
            </span>
        </button>

        <?php if (!$block->getDisabled()): ?>
            <ul class="dropdown-menu" <?php /* @noEscape */ echo $block->getUiId("dropdown-menu"); ?>>
                <?php foreach ($block->getOptions() as $key => $option): ?>
                    <li>
                    <span <?php /* @noEscape */ echo $block->getOptionAttributesHtml($key, $option); ?>>
                        <?php /* @noEscape */ echo $block->escapeHtml($option['label']); ?>
                    </span>
                        <?php if (isset($option['hint'])): ?>
                            <div class="tooltip" <?php /* @noEscape */ echo $block->getUiId('item', $key, 'tooltip'); ?>>
                                <a href="<?php /* @noEscape */ echo $block->escapeHtml($option['hint']['href']) ?>" class="help">
                                    <?php /* @noEscape */ echo $block->escapeHtml($option['hint']['label']) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</div>

<script>
    require(['jquery'], function($){
        $('.actions-split')
            .on('click.splitDefault', '.action-default', function() {
                $(this).siblings('.dropdown-menu').find('.item-default').trigger('click');
            });
    });
</script>
