<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Amazon\Listing\View\Sellercentral\Repricing\RegularPricePopup $block */

?>

<div id="regular_price_popup">
    <div style="padding: 10px;">
        <?php echo $block->__('
            Some of the selected Products will not be added to Amazon Repricing Tool since B2C Price is not specified for them. Only Products with B2C Price can be repriced.
        '); ?>
    </div>
</div>
