<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo $block->__('Main Checks'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $block->mainChecks; ?>
        </td>
    </tr>
</table>