<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<table class="data-grid">
    <thead>
    <tr style="border-top: 0.1rem solid #d6d6d6;">
        <td>
            <?php echo $block->__('From Version') ?>
        </td>
        <td>
            <?php echo $block->__('To Version') ?>
        </td>
        <td>
            <?php echo $block->__('Date') ?>
        </td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->setupData as $setupRow) : ?>
        <tr>
            <td>
                <?php echo $setupRow['version_from'] ?>
            </td>
            <td>
                <?php echo $setupRow['version_to'] ?>
            </td>
            <td>
                <?php echo $setupRow['create_date'] ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>