<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo $block->__('Host'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $block->locationHost; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $block->__('Domain'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $block->locationDomain; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $block->__('IP'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $block->locationIp; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $block->__('Directory'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $block->locationDirectory; ?>
        </td>
    </tr>

</table>