<?php

/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Template\SellingFormat\PriceChange $block */

$type = $block->getPriceType();
$typeForDataset = str_replace('_', '-', $type);
$priceModifierData = $block->getPriceModifier();

$attributes = $block->getAllAttributes();
$priceModifierAttributes = $block->getPriceModifierAttributes($priceModifierData);
$attributesByInputTypes = $block->getAttributesByInputTypes();

?>

<div id="<?=$type?>_change_container"></div>
<div id="<?=$type?>_calculation_example" class="price_change_row" style="display: none;"></div>
<button title="<?php echo $block->__('Add Price Change'); ?>"
        id="<?=$type?>_change_add_row_button"
        type="button"
        class="action-default scalable action primary price_change_remove price_change_additional_element">
    <span><?php echo $block->__('Add Price Change'); ?></span>
</button>

<div id="<?=$type?>_change_row_template" style="display: none;">
    <div style="position: relative;" class="price_change_row">
        <select id="<?=$type?>_modifier_mode_%index%"
                name="<?=$type?>_modifier_mode[%index%]"
                class="select admin__control-select M2ePro-validate-price-modifier price_modifier_mode required-entry"
                data-<?=$typeForDataset?>-change-index="%index%"
                style="width: 250px;">
            <option
                value="<?php echo \Ess\M2ePro\Model\Template\SellingFormat::PRICE_MODIFIER_ABSOLUTE_INCREASE; ?>">
                <?php echo $block->__('Absolute Value increase'); ?></option>
            <option
                value="<?php echo \Ess\M2ePro\Model\Template\SellingFormat::PRICE_MODIFIER_ABSOLUTE_DECREASE; ?>">
                <?php echo $block->__('Absolute Value decrease'); ?></option>
            <option
                value="<?php echo \Ess\M2ePro\Model\Template\SellingFormat::PRICE_MODIFIER_PERCENTAGE_INCREASE; ?>">
                <?php echo $block->__('Percentage increase'); ?></option>
            <option
                value="<?php echo \Ess\M2ePro\Model\Template\SellingFormat::PRICE_MODIFIER_PERCENTAGE_DECREASE; ?>">
                <?php echo $block->__('Percentage decrease'); ?></option>
            <option
                value="<?php echo \Ess\M2ePro\Model\Template\SellingFormat::PRICE_MODIFIER_ATTRIBUTE_INCREASE; ?>">
                <?php echo $block->__('Increase by Attribute Value'); ?></option>
            <option
                value="<?php echo \Ess\M2ePro\Model\Template\SellingFormat::PRICE_MODIFIER_ATTRIBUTE_DECREASE; ?>">
                <?php echo $block->__('Decrease by Attribute Value'); ?></option>
        </select>

        <div style="width: 250px; display: inline-block">
            <input name="<?=$type?>_modifier_value[%index%]"
                   id="<?=$type?>_modifier_value_%index%"
                   type="text"
                   class="admin__control-text input-text coef price_change_additional_element M2ePro-required-when-visible"
                   style="width: 100%"/>

            <select id="<?=$type?>_modifier_attribute_%index%"
                    name="<?=$type?>_modifier_attribute[%index%]"
                    class="select admin__control-select M2ePro-validate-price-modifier price_modifier_mode M2ePro-required-when-visible"
                    data-<?=$typeForDataset?>-change-index="%index%"
                    style="width: 100%">

                <?php foreach ($priceModifierAttributes as $attributeCode): ?>
                    <?php if(!$block->magentoAttributeHelper->isExistInAttributesArray($attributeCode, $attributes)): ?>
                        <option value="<?php echo $attributeCode; ?>">
                            <?php echo $block->escapeHtml($block->magentoAttributeHelper->getAttributeLabel($attributeCode)); ?>
                        </option>
                    <?php endif; ?>
                <?php endforeach; ?>

                <?php foreach ($attributesByInputTypes['text_price'] as $attribute) : ?>
                    <option value="<?php echo $attribute['code']; ?>">
                        <?php echo $block->escapeHtml($attribute['label']); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <button title="<?php echo $block->__('Remove'); ?>"
                id="<?=$type?>_modifier_row_remove_button_%index%"
                type="button"
                class="action-default scalable action primary price_change_remove price_change_additional_element">
            <span><?php echo $block->__('Remove'); ?></span>
        </button>
    </div>
</div>
