<?php

/**
 * @var \Ess\M2ePro\Block\Adminhtml\Walmart\Template\SellingFormat\Edit\Form\RepricerStrategy $block
 */

$element = $this->getElement();

?>

<style>
    .flex-row {
        display: flex;
        gap: 10px;
        align-items: center;
    }
</style>
<table class="border data-grid data-grid-not-hovered" style="margin: auto">
    <thead>
    <tr class="headings">
        <th class="data-grid-th">
            <?= /* @noEscape */ __('Account') ?>
        </th>
        <th class="data-grid-th">
            <?= /* @noEscape */ __('Repricer Strategy') ?>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getAccounts() as $account) : ?>
        <tr>
            <td><?= /* @noEscape */ $account->getTitle() ?></td>
            <td>
                <div class="flex-row">
                    <div style="margin-right: 40px">
                        <?= /* @noEscape */ $block->createDropDown($account) ?>
                    </div>
                    <?= /* @noEscape */ $block->createRefreshLink($account) ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script>
    require([
        'M2ePro/Walmart/Template/SellingFormat/RepricerStrategy'
    ], function () {
        new WalmartTemplateSellingFormatRepricerStrategy({
            refreshButtonSelector: '.refresh_account_repricer_strategy',
            selectPrefix: 'repricer_strategy_select_',
            getStrategiesUrl: '<?= /* @noEscape */ $block->getStrategiesUrl() ?>'
        });
    })
</script>

