<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

/** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Tabs\ChangeTracker $block */

?>

<div class="page-layout-admin-2columns-left" style="margin-top: 20px;">
    <div class="page-columns">
        <div class="main-col">
            <div id="change_tracker_tabs">
            </div>
        </div>
        <div class="side-col">
            <?php /* @noEscape */ echo $block->getChildHtml('tabs'); ?>
        </div>
    </div>
</div>
