<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

/** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Tabs\ChangeTracker\Logs $block */

?>
<div>
    <h2>Logs</h2>
    <hr>
    <?php foreach ($block->logs as $logsIndex => $logs) : ?>
    <div style="margin-bottom: 20px">
        <?php if ($logs === []) {
            continue;
        } ?>
        <h3>Logs #<?= ++$logsIndex ?></h3>
        <?php foreach ($logs as $i => $log) : ?>
            <div class="log-box <?= /* @noEscape */ $i%2 === 0 ? 'even' : 'odd' ?>">
                <div>
                    <span class="log-datetime"><?= /* @noEscape */ $log['date'] ?></span>
                    <span class="log-level">[<?= /* @noEscape */ $log['level'] ?? '' ?>]</span>
                    <span class="log-message"><?= /* @noEscape */ $log['message'] ?></span>
                </div>
                <?php if ($log['context'] !== '[]') : ?>
                    <textarea rows="10" class="log-context"><?= /* @noEscape */ $log['context'] ?></textarea>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
</div>
