<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Amazon\Listing\Product\Add\NewAsin\Manual\SkipPopup $block */

?>

<div id="new_asin_skip_popup_content">

    <div style="margin-top: 10px;">
        <?php /* @noEscape */ echo $block->__(
            '<b>Warning:</b> There are <span id="failed_count"></span> Product(s) of <span id="total_count"></span> which have no Product Type assigned.<br/><br/>

            If you want to assign Product Type now, click<strong>Cancel</strong>then choose the Set Product Type Action for the Products which need them.<br/><br/>

            If you\'re not ready to add Product Type yet or you are not sure which Product Type to choose, click<strong>Continue</strong>.
            You will have a chance to assign Product Types later in the M2E Pro Listing Settings. '
        ); ?>
    </div>

</div>
