<div id="new_asin_skip_popup_content">

    <div style="margin-top: 10px;">
        <?php echo $block->__(
            '<b>Warning:</b> There are <span id="failed_count"></span> Product(s) of <span id="total_count"></span> which have no Description Policy assigned.<br/><br/>

            If you want to assign Description Policy now, click <strong>Cancel</strong> then choose the Set Description Policy Action for the Products which need them.<br/><br/>

            If you\'re not ready to add Description Policy yet or you are not sure which Description Policy to choose, click <strong>Continue</strong>.
            You will have a chance to assign Description Policies later in the M2E Pro Listing Settings. '
        ); ?>
    </div>

</div>