<?php
/** @var $block \Ess\M2ePro\Block\Adminhtml\Walmart\Account\Edit\Tabs\Order\PrefixesTable  */
?>

<style>
    div.admin__field.field-magento_orders_number_prefix_container.m2epro-fieldset-table,
    div.field-magento_orders_number_prefix_container div.admin__field-control {
        margin: 0 !important;
    }
    #magento_orders_number_prefix_container table div.note span {
        font-weight: bold;
    }
    #magento_orders_number_prefix_container table input {
        width: 350px !important;
        margin-right: 100px;
    }
    #magento_orders_number_prefix_container table td {
        margin-right: 100px;
        margin-left: 50px;
    }
    .prefix-label {
        clear: both;
        color: #303030;
        display: block;
        font-size: 1.7rem;
        font-weight: 600;
        letter-spacing: .025em;
        padding: 1.9rem 2.8rem 1.9rem 0;
        position: relative;
    }
</style>

<div class="admin__control-table-wrapper">
    <input type="hidden" id="sample_magento_order_id" value="<?php /* @noEscape */ echo $block->getSampleMagentoOrderId(); ?>" />
    <input type="hidden" id="sample_walmart_order_id" value="141-4423723-6495633" />
    <span class="prefix-label"><?php /* @noEscape */ echo $block->__('Prefix for magento order number'); ?></span>
    <table class="admin__control-table">
        <thead>
        <tr>
            <th class="label-wrapper"><?php /* @noEscape */ echo $block->__('General'); ?></th>
            <th class="label-wrapper"><?php /* @noEscape */ echo $block->__('WFS'); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="prefix-column-wrapper">
                <input
                    id="magento_orders_number_prefix_prefix"
                    class="input-text" type="text"
                    name="magento_orders_settings[number][prefix][prefix]"
                    value="<?php /* @noEscape */ echo $block->getMagentoOrderPrefix(); ?>" />
                <div class="note admin__field-note">e.g. <span id="order_number_example_container_prefix"></span></div>
            </td>
            <td class="prefix-column-wrapper">
                <input
                    id="magento_orders_number_prefix_wfs"
                    class="input-text" type="text"
                    name="magento_orders_settings[number][prefix][wfs-prefix]"
                    value="<?php /* @noEscape */ echo $block->getMagentoOrderPrefixWFS(); ?>" />
                <div class="note admin__field-note">e.g. <span id="order_number_example_container_wfs"></span></div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
