<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo $this->__('Total Tables'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlTotal['magento_tables']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('Total Module Tables'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlTotal['module_tables']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('Total Module Records'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlTotal['module_records']; ?>
        </td>
    </tr>

</table>