<?php /** @var \Ess\M2ePro\Block\Adminhtml\Dashboard\Errors $block */ ?>

<div class="cards">
    <?php foreach ($block->getCardItems() as $item): ?>
        <?php if($item['url']): ?>
            <a href="<?= /* @noEscape */ $item['url'] ?>" target="_blank" class="card-item">
                <h4><?= /* @noEscape */ $item['title'] ?></h4>
                <p><?= /* @noEscape */ $item['value'] ?></p>
            </a>
        <?php else: ?>
            <div class="card-item">
                <h4><?= /* @noEscape */ $item['title'] ?></h4>
                <p><?= /* @noEscape */ $item['value'] ?></p>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
