<?php /** @var \Ess\M2ePro\Block\Adminhtml\Dashboard\ListingProductIssues $block */ ?>

<?php if ($notificationMessage = $block->getNotificationMessage()): ?>
    <p><?= /* @noEscape */ $notificationMessage ?></p>
<?php endif; ?>

<?php if ($block->isIssuesTableVisible()): ?>

    <table class="admin__table-primary" id="dashboard_listing_product_issues">
        <thead>
            <tr>
                <th class="data-grid-th"><span><?= /* @noEscape */ __('Issues') ?></span></th>
                <th class="data-grid-th issues-total"><span><?= /* @noEscape */ __('Items') ?></span></th>
                <th class="data-grid-th issues-impact-rate"><span><?= /* @noEscape */ __('Impact Rate') ?></span></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($block->getIssues() as $issue): ?>
                <tr title="<?= /* @noEscape */ $issue['url'] ?>" data-url="<?= /* @noEscape */ $issue['url'] ?>" class="issues-row issues-cursor">
                    <td class="issues-text"><?= /* @noEscape */ $issue['text'] ?></td>
                    <td class="issues-total"><?= /* @noEscape */ $issue['total'] ?></td>
                    <td class="issues-impact-rate"><?= /* @noEscape */ $issue['impact_rate'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php if ($viewMoreUrl = $block->getItemsByIssueViewUrl()): ?>
        <button id="dashboard_listing_product_issues_view_more" data-url="<?= /* @noEscape */ $viewMoreUrl ?>" title="View more" type="button" class="action-default scalable action-primary issues-view-more-btn">
            <span><?= /* @noEscape */ __('View more') ?></span>
        </button>
    <?php endif; ?>

<?php endif; ?>
