<?php /** @var \Ess\M2ePro\Block\Adminhtml\Dashboard\Shipments $block */ ?>

<div class="cards">
    <?php foreach ($block->getCardItems() as $item): ?>
        <a href="<?= /* @noEscape */ $item['url'] ?>" target="_blank" class="card-item">
            <h4><?= /* @noEscape */ $item['title'] ?></h4>
            <p><?= /* @noEscape */ $item['value'] ?></p>
        </a>
    <?php endforeach; ?>
</div>
