<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo $this->__('Host'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationHost; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('Domain'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationDomain; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('IP'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationIp; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('Directory'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationDirectory; ?>
        </td>
    </tr>

</table>