<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo $this->__('Name'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->moduleName; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('Version'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->moduleVersion; ?>
        </td>
    </tr>

</table>