<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo $this->__('Name'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->systemName; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo $this->__('Current Date'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->systemTime; ?>
        </td>
    </tr>

</table>