<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

$selectedCategory = $block->getSelectedCategory();
?>

<div id="selected_category_container">
    <table>
        <tr>
            <td>
                <strong id="category_title_container"><?php /* @noEscape */ echo $block->__('Category'); ?>:</strong>
            </td>
            <td>
                <span id="selected_category_path">
                    <?php if (!empty($selectedCategory)) : ?>
                        <?php /* @noEscape */ echo $block->escapeHtml("{$selectedCategory['categoryPath']} ({$selectedCategory['browseNodeId']})"); ?>
                    <?php else : ?>
                        <span style="color: grey; font-style: italic"><?php /* @noEscape */ echo $block->__('Not Selected'); ?></span>
                    <?php endif; ?>
                </span>
            </td>
            <td>
                <a href="javascript:void(0)" id="category_reset_link" <?php if (empty($selectedCategory)) :
                    ?>style="display: none"<?php
                                                                      endif; ?> onclick="WalmartTemplateCategoryCategoriesChooserObj.unSelectCategory()"><?php /* @noEscape */ echo $block->__('Reset') ?></a>
            </td>

        </tr>
    </table>
</div>

<input type="hidden" id="category_validation" value="" class="required-entry">
