<?php
/**
 * @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Description\Edit\Form\ComplianceDocuments\FormElementRender $this
 * @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Description\Edit\Form\ComplianceDocuments\FormElement $element
 */

$element = $this->getElement();

?>

<div class="admin__field documents_block_wrapper">
    <label class="label admin__field-label"></label>
    <div id="documents_table_wrapper" class="admin__field-control control">
        <table>
            <colgroup>
                <col style="width: 40%">
                <col style="width: 40%">
                <col style="width: 20%">
            </colgroup>
            <thead>
                <tr>
                    <th><span><?= __('Type') ?></span></th>
                    <th><span><?= __('Document URL') ?></span><?= $element->getTooltipHtml() ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($element->getSavedComplianceDocuments() as $index => $document) : ?>
            <tr>
                <td><?= $element->renderTypesDropdown($index, $document['document_type']) ?></td>
                <td><?= $element->renderAttributesDropdown($index, $document['document_attribute']) ?></td>
                <td><?= $element->renderRemoveRowButton($index) ?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?= $element->renderAddRowButton() ?>
    </div>
</div>


