<?php
/**
 * @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Description\Edit\Form\ComplianceDocuments\FormElementRender $this
 * @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Description\Edit\Form\ComplianceDocuments\FormElement $element
 */

$element = $this->getElement();

?>

<div class="admin__field documents_block_wrapper">
    <div id="documents_table_wrapper">
        <table class="documents-table border data-grid data-grid-not-hovered">
            <colgroup>
                <col style="width: 30%">
                <col style="width: 20%">
                <col style="width: 30%">
                <col style="width: 20%">
            </colgroup>
            <thead>
                <tr>
                    <th class="data-grid-th"><span><?= /* @noEscape */ __('Type') ?></span></th>
                    <th class="data-grid-th"><span><?= /* @noEscape */ __('Mode') ?></span></th>
                    <th class="data-grid-th">
                        <span><?= /* @noEscape */ __('Document URL') ?></span>
                        <?= /* @noEscape */ $element->getTooltipHtml(__('Choose an Attribute containing a valid URL ' .
                            'for the selected Document Type')) ?>
                    </th>
                    <th class="data-grid-th">
                        <span><?= /* @noEscape */ __('Languages') ?></span>
                        <?= /* @noEscape */ $element->getTooltipHtml(__('Select one or more languages used in the document.')) ?>
                    </th>
                    <th class="data-grid-th"></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($element->getSavedComplianceDocuments() as $index => $document) : ?>
            <?php $mode = (int)$document['document_mode']?>
            <tr>
                <td><?= /* @noEscape */ $element->renderTypesDropdown($index, $document['document_type']) ?></td>
                <td><?= /* @noEscape */ $element->renderModeDropdown($index, $mode) ?></td>
                <td>
                    <?= /* @noEscape */ $element->renderAttributesDropdown($index, $document['document_attribute'], $mode) ?>
                    <?= /* @noEscape */ $element->renderCustomValueInput($index, $document['document_custom_value'] ?? '', $mode) ?>
                </td>
                <td><?= /* @noEscape */ $element->renderLanguagesDropdown($index, $document['document_languages'] ?? []) ?></td>
                <td><?= /* @noEscape */ $element->renderRemoveRowButton($index) ?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" style="text-align:right;"><?= /* @noEscape */ $element->renderAddRowButton() ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>


