<?php /** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Description\Preview $this */ ?>

<div class="pagination_container page-main-actions">
    <div class="product_title">
        <h2><?php echo $this->getData('title'); ?> (ID: <?php echo $this->getData('magento_product_id'); ?>)</h2>
    </div>
</div>

<div class="description_container">
    <?php echo $this->getData('description'); ?>
</div>
