<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\PageHelpLink $block */

?>

<div class="m2epro-page-help-link m2epro-field-tooltip-to-right admin__field-tooltip">
    <a class="admin__field-tooltip-action" href="<?php echo $block->getPageHelpLink(); ?>" target="_blank"></a>
    <div class="admin__field-tooltip-content">
        <?php echo $block->__('Click here to get help for this page.'); ?>
    </div>
</div>
