<?php /** @var \Ess\M2ePro\Block\Adminhtml\Renderer\Description\Gallery $this */ ?>

<?php $data = $this->getData(); ?>

<?php if ($data['linked_mode'] == \Ess\M2ePro\Helper\Module\Renderer\Description::IMAGES_MODE_GALLERY): ?>

    <?php if ($data['image_counter'] == 1): ?>

        <style type="text/css">
            .gallery-thumbnail {
                padding: 0;
                margin: 0;
                display: table;
            }
            .gallery-image {
                margin-bottom: 20px;
            }
            .gallery-image div {
                margin-top: 10px;
            }
            .gallery-thumbnail li {
                list-style: none;
                margin: 5px;
                text-align: right;
            }
            .gallery-column-view .gallery-thumbnail {
                width: 20%;
                float: left;
            }
            .gallery-column-view .gallery-image {
                width: 78%;
                float: right;
                text-align: left;
            }
            .gallery-row-view .gallery-thumbnail li {
                float: left;
            }
        </style>

    <?php $galleryClass = $data['layout'] == \Ess\M2ePro\Helper\Module\Renderer\Description::LAYOUT_MODE_COLUMN ? 'gallery-column-view' : 'gallery-row-view'; ?>
    <center class="<?php echo $galleryClass; ?>">
        <div class="gallery-image">
            <img name="view<?php echo $data['attribute_counter']; ?>" id="image<?php echo $data['attribute_counter']; ?>" src="<?php echo $data['src']; ?>"<?php if ($data['width'] != ''): echo " width={$data['width']}"; endif; ?><?php if ($data['height'] != ''): echo " height={$data['height']}"; endif; ?><?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?> style="<?php if ($data['margin'] != ''): echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?>" />
            <br/>
            <div style="<?php if ($data['width'] != ''): echo "width: {$data['width']}px"; endif; ?>">
                <?php echo $this->getHelper('Data')->escapeHtml($data['gallery_hint']); ?>
            </div>
        </div>

        <ul class="gallery-thumbnail">

    <?php endif; ?>

            <li>
                <img width="68" height="68" style="cursor: pointer;" onclick="document.images['view<?php echo $data['attribute_counter']; ?>'].src='<?php echo $data['src']; ?>';" src="<?php echo $data['src']; ?>"<?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?> />
            </li>

    <?php if ($data['image_counter'] == $data['images_count']): ?>

        </ul>
    </center>

    <?php endif; ?>

<?php else: ?>

    <?php if ($data['linked_mode'] == \Ess\M2ePro\Helper\Module\Renderer\Description::IMAGES_MODE_NEW_WINDOW): ?>
        <a href="<?php echo $data['src']; ?>" target="_blank"<?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?>>
    <?php endif; ?>

        <img src="<?php echo $data['src']; ?>"<?php if ($data['width'] != ''): echo ' width="'.$data['width'].'"'; endif; ?><?php if ($data['height'] != ''): echo ' height="'.$data['height'].'"'; endif; ?><?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?> style="<?php if ($data['margin'] != ''): echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?><?php if ($data['linked_mode'] == \Ess\M2ePro\Helper\Module\Renderer\Description::IMAGES_MODE_NEW_WINDOW): echo ' cursor: pointer; border: none;'; endif; ?>" />

    <?php if ($data['linked_mode'] == \Ess\M2ePro\Helper\Module\Renderer\Description::IMAGES_MODE_NEW_WINDOW): ?>
        </a>
    <?php endif; ?>

    <?php if ($data['layout'] == \Ess\M2ePro\Helper\Module\Renderer\Description::LAYOUT_MODE_COLUMN): ?>
        <br/>
    <?php endif; ?>

<?php endif; ?>