<?php
/** @var \Ess\M2ePro\Block\Adminhtml\Renderer\Description\Image $this */
$data = $this->getData();
?>

    <style>

        #m2e-description-image-<?php echo $this->getImageId(); ?> {
        <?php if ($data['width'] != 0) : echo "width: {$data['width']}px;"; endif; ?>
        <?php if ($data['height'] != 0) : echo "height: {$data['height']}px;"; endif; ?>
        <?php if ($data['margin'] != 0) : echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?>
        }

    </style>

<?php if ($this->isLinkMode()) { ?>
    <a href="<?php echo $data['src']; ?>" target="_blank"<?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?> style="cursor: pointer;">
<?php } ?>

    <img src="<?php echo $data['src']; ?>"
         border="0"
        <?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?>
         id="m2e-description-image-<?php echo $this->getImageId(); ?>"
    />

<?php if ($this->isLinkMode()) { ?>
    </a>
<?php } ?>