<?php /** @var \Ess\M2ePro\Block\Adminhtml\Renderer\Description\Image $this */ ?>

<?php $data = $this->getData(); ?>

<?php if ($data['linked_mode'] == \Ess\M2ePro\Helper\Module\Renderer\Description::IMAGES_MODE_NEW_WINDOW) { ?>
    <a href="<?php echo $data['src']; ?>" target="_blank"<?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?> style="cursor: pointer;">
<?php } ?>

<img src="<?php echo $data['src']; ?>" border="0"<?php if ($data['width'] != 0): echo ' width="'.$data['width'].'"'; endif; ?><?php if ($data['height'] != 0): echo ' height="'.$data['height'].'"'; endif; ?><?php if ($data['watermark'] != 0): echo ' m2e_watermark="1"'; endif; ?> style="<?php if ($data['margin'] != 0): echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?>" />

<?php if ($data['linked_mode'] == \Ess\M2ePro\Helper\Module\Renderer\Description::IMAGES_MODE_NEW_WINDOW) { ?>
    </a>
<?php } ?>