<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Amazon\Listing\Product\Variation\SwitchToParentPopup $block */

?>

<div id="switch_to_parent_popup">
    <style>
        .list {
            margin: 10px 0px !important;
            padding-left: 30px !important;
            list-style: disc outside;
        }
    </style>

    <?php echo $block->createBlock('HelpBlock')->setData([
        'no_collapse' => true,
        'no_hide' => true,
        'always_show' => true,
        'style' => 'margin-bottom: 0px',
        'content' => $block->__(
            'You can sell Magento Variational Product on Amazon in two different ways:
            <ul class="list">
                <li>as Amazon Variational Product using Parent/Child Mode;</li>
                <li>as Amazon Individual Product using Individual Mode.</li>
            </ul>
            Find more details <a href="%url%" target="_blank" class="external-link">here</a>. <br/>

            This Product is currently managed under <strong>Individual Mode</strong>. Do you want to switch it to 
            <strong>Parent/Child Mode</strong>? <br/>',
            $block->getHelper('Module\Support')->getDocumentationArticleUrl('x/OwgtAQ')
        )
    ])->toHtml(); ?>

    <div class="admin__field admin__field-option" style="position: absolute; margin-left: 10px; margin-top: 30px;">
        <input class="admin__control-checkbox" type="checkbox" id="switch_to_parent_remember_checkbox" name="switch_to_parent_remember_checkbox">&nbsp;
        <label for="switch_to_parent_remember_checkbox" class="admin__field-label">
            <span><?php echo $block->__('Remember my choice') ?></span>
        </label>
    </div>

</div>