<div id="vocabulary_attributes_pupup" style="display: none;">
    <div style="margin-top: 10px;">
        <?php echo $block->__('
        You have just specified an accordance between <strong>Magento Variational Attribute</strong> and
        <strong>Amazon Variational Attribute</strong> that was not defined earlier. M2E Pro can remember
        Attributes match below and use them in future automatically.<br/><br/>

        %attributes%<br/>

        Do you want M2E Pro to <strong>remember</strong> this match and use it <strong>automatically</strong> in future?<br/><br/>
        '); ?>

        <input type="hidden" id="vocabulary_attributes_data" value="">

        <div class="admin__field admin__field-option" style="position: absolute; margin-top: 30px;">
            <input class="admin__control-checkbox" type="checkbox" id="vocabulary_attributes_remember_checkbox">
            &nbsp;&nbsp;
            <label for="vocabulary_attributes_remember_checkbox" class="admin__field-label">
                <span><?php echo $block->__('Remember my choice') ?></span>
            </label>
        </div>
    </div>

</div>