<script type="application/javascript">
    AmazonListingVariationProductManageHandlerObj = new CommonAmazonListingVariationProductManageHandler();
</script>

<div id="vocabulary_options_pupup_template" style="display: none;">
    <div style="padding: 10px;">
        <?php echo $this->__('
        You have just specified an accordance between <strong>Magento Variational Option</strong> and
        <strong>Amazon Variational Option</strong> that was not defined earlier. M2E Pro can remember Options match
        below and use them in future automatically for that Attribute.<br/><br/>

        %options%<br/>

        Do you want M2E Pro to <strong>remember</strong> this match and use it <strong>automatically</strong> in future?<br/><br/>
        '); ?>

        <input type="hidden" id="vocabulary_options_data" value="">

        <div class="clear"></div>
        <div class="left">
            <div style="margin-left: 20px">
                <input id="vocabulary_options_remember_checkbox" type="checkbox">
                &nbsp;&nbsp;
                <label for="vocabulary_options_remember_checkbox"><?php echo $this->__('Remember my choice') ?></label>
            </div>
        </div>
        <div class="right">
            <?php echo $this->getChildHtml('yes_btn'); ?>
            <div style="display: inline-block;"></div>
            <?php echo $this->getChildHtml('no_btn'); ?>
        </div>
        <div class="clear"></div>
    </div>

</div>