<?php
    /** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Tabs\Cron $this */
?>

<style>
    .group_container_summary_cron .fieldset-wrapper .form-list {
        font-size: 13px;
    }
    .group_container_summary_cron .fieldset-wrapper td.label {
        width: 420px !important;
    }

    .group_container_summary_cron .form-list tr:hover {
        background-color: #f5f5f5;
    }

    .group_container_summary_cron .form-list td {
        padding-left: 15px;
        padding-right: 15px;
    }
</style>

<div class="entry-edit group_container_summary group_container_summary_cron">

    <div class="control_panel_head_container">
        <h4>Run Task</h4>
    </div>

    <div class="col-m-12 controlPanel__block_container">
        <div class="fieldset-wrapper">

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">
                    <table class="form-list" cellspacing="0" cellpadding="0">
                        <tr>
                            <td class="label">Run All</td>
                            <td class="value">
                                <a href="<?= $this->getRunAllUrl() ?>" target="_blank">Run</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <?php foreach ($this->tasks as $group => $tasks) : ?>
        <div class="col-m-4 controlPanel__block_container" style="width: 30%; min-width: 500px;">
            <div class="fieldset-wrapper">

                <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                    <h4><?= $group ?></h4>
                </div>

                <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                    <div class="hor-scroll">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <?php foreach ($tasks as $taskCode => $taskTitle) : ?>
                                <tr>
                                    <td class="label"><?= $taskTitle ?></td>
                                    <td class="value">
                                        <a href="<?= $this->getTaskUrl($taskCode) ?>" target="_blank">Run</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
