<?php
    /** @var \Ess\M2ePro\Block\Adminhtml\ControlPanel\Tabs\Cron $block */
?>

<style>
    :root {
        --loader-image-url: url('<?= /* @noEscape */ $block->getViewFileUrl('images/loader-2.gif') ?>');
    }
</style>

<div class="cron-tab-container" data-mage-init='{
    "Ess_M2ePro/js/ControlPanel/CronTab": {
        "moduleIdentifier": "<?= /* @noEscape */ $block->getModuleIdentifier() ?>",
        "cronRunUrl": "<?= /* @noEscape */ $block->getCronRunUrl() ?>"
    }
}'>
    <div class="run-task-section" style="">
        <div class="header">
            <h3>Run Task</h3>
        </div>

        <div class="run-task-form">
            <label for="task_code">Task Name:</label>

            <div class="dropdown-container">
                <div class="dropdown-trigger" id="dropdown-trigger">
                    <div class="trigger-text"></div>
                    <div class="trigger-arrow-btn"></div>
                </div>

                <div class="dropdown-menu" id="dropdown-menu">
                    <div class="dropdown-item" data-value="">Run All Tasks</div>

                    <?php foreach ($block->getTasks() as $groupName => $tasks) : ?>
                        <div class="dropdown-group-header">
                            <span><?= /* @noEscape */ $groupName; ?></span>
                            <button class="run-group-btn" data-group="<?= /* @noEscape */ $groupName; ?>">Run</button>
                        </div>
                        <?php foreach ($tasks as $taskCode => $taskTitle) : ?>
                        <div class="dropdown-item"
                             data-value="<?= /* @noEscape */ $taskCode; ?>"
                             data-group="<?= /* @noEscape */ $groupName; ?>"
                        ><?= /* @noEscape */ $taskTitle; ?></div>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </div>
            </div>

            <div>
                <button id="run_task" class="action-primary">Run</button>
                <button id="add_to_queue">Add to Sequence</button>
            </div>
        </div>

    </div>

    <div style="display: flex; gap: 2rem;">
        <div class="scenario-section">
            <div class="header">
                <h3>Scenario Queue</h3>
                <div class="scenario-controls">
                    <button class="action-primary" id="run-scenario">Run Scenario</button>
                    <button id="clear-queue">Clear Queue</button>
                </div>
            </div>

            <ul id="queue_list" class="list-queue"></ul>

            <div class="hint">
                * You can drag and drop items to reorder the execution sequence.
            </div>
        </div>

        <div class="results-card">
            <div class="header">
                <h3>Execution Results</h3>
            </div>
            <pre id="execution-results"></pre>
        </div>
    </div>
</div>
