<div id="magento_block_control_panel_debug_commands" class="debug-test-commands">

    <?php foreach($this->commands as $command) : ?>

        <table class="simple_commands_list">

            <tr>
                <td>

                    <a href="<?php echo $command['url']; ?>" <?php if ($command['confirm'] != ''): ?>onclick="return confirm('<?php echo $command['confirm']; ?>');"<?php endif; ?> <?php if ($command['new_window']): ?>target="_blank"<?php endif; ?> title="<?php echo $command['description']; ?>" alt="<?php echo $command['description']; ?>"><?php echo $command['title']; ?></a>
                    <p style="font-size: 0.9em; color: grey;"><?php echo $command['description']; ?></p>

                </td>
            </tr>

        </table>

    <?php endforeach; ?>

</div>

<div id="block_notice_control_panel_tab_debug_magento_development" class="debug-mode-switcher">

    <?php if ($this->isMagentoDevelopmentModeEnabled) : ?>
        <b><?php echo $this->__('Magento Development Mode is <span style="color:red;">Enabled</span> now.'); ?></b>
    <?php endif; ?>

    <?php if (!$this->isMagentoDevelopmentModeEnabled) : ?>
        <b><?php echo $this->__('Magento Development Mode is <span style="color:green;">Disabled</span> now.'); ?></b>
    <?php endif; ?>

</div>

<div id="block_notice_control_panel_tab_development_mode" class="debug-mode-switcher">

    <?php if ($this->isDevelopmentModeEnabled) : ?>
        <b><?php echo $this->__('M2E Pro Development Mode is <span style="color:red;">Enabled</span> now.'); ?></b>
        <div style="float: right; margin-top: -9px;">
            <?php echo $this->getChildHtml('disable_development_mode'); ?>
        </div>
    <?php endif; ?>

    <?php if (!$this->isDevelopmentModeEnabled) : ?>
        <b><?php echo $this->__('M2E Pro Development Mode is <span style="color:green;">Disabled</span> now.'); ?></b>
        <div style="float: right; margin-top: -9px;">
            <?php echo $this->getChildHtml('enable_development_mode'); ?>
        </div>
    <?php endif; ?>

</div>

<div id="block_notice_control_panel_tab_debug_maintenance" class="debug-mode-switcher">

    <?php if ($this->isMaintenanceEnabled) : ?>
        <b><?php echo $this->__('Debug Maintenance is <span style="color:red;">Enabled</span> now.'); ?></b>
        <div style="float: right; margin-top: -9px;">
            <?php echo $this->getChildHtml('disable_maintenance'); ?>
        </div>
    <?php endif; ?>

    <?php if (!$this->isMaintenanceEnabled) : ?>
        <b><?php echo $this->__('Debug Maintenance is <span style="color:green;">Disabled</span> now.'); ?></b>
        <div style="float: right; margin-top: -9px;">
            <?php echo $this->getChildHtml('enable_maintenance'); ?>
        </div>
    <?php endif; ?>

</div>