<!-- ########################################################################################### -->

<style>

    span.red {
        color: red;
    }

</style>

<!-- ########################################################################################### -->

<div class="col-m-6 controlPanel__block_container">

    <?php if ($this->getChildBlock('requirements')->isShown()) { ?>
        <div class="fieldset-wrapper" id="magento_block_control_panel_inspection_requirements">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <h4><?php echo $this->__('System Requirements'); ?></h4>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('requirements') ?>

                </div>
            </div>

        </div>
    <?php } ?>

    <?php if ($this->getChildBlock('caches')->isShown()) { ?>
        <div class="fieldset-wrapper" id="magento_block_control_panel_inspection_caches">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <h4><?php echo $this->__('Caches / Configs'); ?></h4>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('caches') ?>

                </div>
            </div>

        </div>
    <?php } ?>

</div>

<!-- ########################################################################################### -->

<div class="col-m-6 controlPanel__block_container">

    <?php if ($this->getChildBlock('cron')->isShown()) { ?>
        <div class="fieldset-wrapper" id="magento_block_control_panel_inspection_cron">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <h4><?php echo $this->__('Cron'); ?></h4>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('cron') ?>

                </div>
            </div>

        </div>
    <?php } ?>

    <?php if ($this->getChildBlock('conflicted_modules')->isShown()) { ?>
        <div class="fieldset-wrapper" id="magento_block_control_panel_inspection_conflicted_modules">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <h4><?php echo $this->__('Conflicted Modules'); ?></h4>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('conflicted_modules') ?>

                </div>
            </div>

        </div>
    <?php } ?>

    <?php if ($this->getChildBlock('database_broken')->isShown()) { ?>
        <div class="fieldset-wrapper" id="magento_block_control_panel_inspection_database_broken">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <h4><?php echo $this->__('Database Broken Tables'); ?></h4>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('database_broken') ?>

                </div>
            </div>

        </div>
    <?php }?>

    <?php if ($this->getChildBlock('other_issues')->isShown()) { ?>
        <div class="fieldset-wrapper" id="magento_block_control_panel_inspection_other_issues">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <h4><?php echo $this->__('Other Issues'); ?></h4>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('other_issues') ?>

                </div>
            </div>

        </div>
    <?php } ?>

</div>

<!-- ########################################################################################### -->