<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<style>
    .fieldset-wrapper .form-list {
        font-size: 13px;
    }
    .fieldset-wrapper td.label {
        width: 220px !important;
    }
</style>

<div class="col-m-4 controlPanel__block_container" style="width: 30%; min-width: 500px;">
    <div class="fieldset-wrapper" id="magento_block_control_panel_info_module">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?php echo $block->__('Information'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('actual_info') ?>
            </div>
        </div>

    </div>

    <div class="fieldset-wrapper" id="magento_block_control_panel_info_location">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?php echo $block->__('License'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('license_info') ?>
            </div>
        </div>

    </div>
</div>

<div class="col-m-3 controlPanel__block_container" style="width: 22%; min-width: 400px;">
    <div class="fieldset-wrapper" id="magento_block_control_panel_database_general">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?php echo $block->__('Database (general)'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('database_general') ?>
            </div>
        </div>

    </div>
</div>

<div class="col-m-3 controlPanel__block_container" style="width: 22%; min-width: 400px;">

    <div class="fieldset-wrapper" id="magento_block_control_panel_database_components">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?php echo $block->__('Database (components)'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('database_components') ?>
            </div>
        </div>

    </div>

</div>

<div class="col-m-4 controlPanel__block_container" style="width: 25%; min-width: 450px;">

    <div class="fieldset-wrapper" id="magento_block_control_panel_info_cron">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?php echo $block->__('Cron'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('cron_info') ?>
            </div>
        </div>

    </div>

    <div class="fieldset-wrapper" id="magento_block_control_panel_info_cron">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?php echo $block->__('Version Info'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('version_info') ?>
            </div>
        </div>

    </div>

</div>