<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Ess\M2ePro\Block\Adminhtml\Magento\Grid\AbstractGrid $block */

/**
 * Template for \Magento\Backend\Block\Widget\Grid
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 */
$numColumns = count($block->getColumns());

/**
 * @var \Ess\M2ePro\Block\Adminhtml\Magento\Grid\AbstractGrid $block
 */
?>
<?php if ($block->getCollection()): ?>
    <?php if ($block->canDisplayContainer()): ?>

    <div id="<?php /* @noEscape */ echo $block->escapeHtml($block->getId()) ?>" data-grid-id="<?php /* @noEscape */ echo $block->escapeHtml($block->getId()) ?>">
        <?php else: ?>
            <?php /* @noEscape */ echo $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
        <?php endif; ?>
        <?php $massActionAvailable = $block->getMassactionBlock() && $block->getMassactionBlock()->isAvailable() ?>
        <?php if ($block->getPagerVisibility() || $block->getExportTypes() || $block->getFilterVisibility() || $massActionAvailable): ?>
            <div class="admin__data-grid-header admin__data-grid-toolbar">
                <div class="admin__data-grid-header-row">
                    <?php /* @noEscape */ echo $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : ''; ?>
                    <?php if ($block->getExportTypes()): ?>
                        <div class="admin__data-grid-export">
                            <label
                                class="admin__control-support-text"
                                for="<?php /* @noEscape */ echo $block->escapeHtml($block->getId()) ?>_export"><?php /* @noEscape */ echo __('Export to:') ?></label>
                            <select name="<?php /* @noEscape */ echo $block->escapeHtml($block->getId()) ?>_export" id="<?php /* @noEscape */ echo $block->escapeHtml($block->getId()) ?>_export"
                                    class="admin__control-select">
                                <?php foreach ($block->getExportTypes() as $_type): ?>
                                    <option value="<?php /* @noEscape */ echo $_type->getUrl() ?>"><?php /* @noEscape */ echo $_type->getLabel() ?></option>
                                <?php endforeach; ?>
                            </select>
                            <?php /* @noEscape */ echo $block->getExportButtonHtml() ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($block->hasAdvancedFilters()) : ?>
                        <div class="data-grid-filters-actions-wrap">
                            <div class="data-grid-filters-action-wrap">
                                <button class="action-default"><?= /* @noEscape */ __('Filters') ?></button>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

                <?php if ($block->hasAdvancedFilters()) : ?>

                    <?php if ($selectedFilters = $block->getSelectedAdvancedFilterColumns()) : ?>
                        <div class="admin__data-grid-filters-current _show">
                            <div class="admin__current-filters-title-wrap">
                                <span class="admin__current-filters-title"><?= /* @noEscape */ __('Active filters') ?>:</span>
                            </div>
                            <div class="admin__current-filters-list-wrap">
                                <ul class="admin__current-filters-list">
                                    <?php foreach ($selectedFilters as $selectedFilter) : ?>
                                        <li><?= /* @noEscape */ $selectedFilter->getSelectedHtml() ?></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="admin__data-grid-filters-wrap">
                        <fieldset class="admin__fieldset admin__data-grid-filters" data-role="filter-form">
                            <?php foreach ($block->getAdvancedFilters() as $filter): ?>
                                <?= /* @noEscape */ $filter->getFilterHtml() ?>
                            <?php endforeach; ?>
                        </fieldset>
                    </div>
                    <script>
                        require(['jquery'], function($) {
                            function getGrid () {
                                return <?= /* @noEscape */ $block->getId() ?>JsObject;
                            }

                            var filterBlock = $('.admin__data-grid-filters-wrap');
                            var filterButton = $('.data-grid-filters-action-wrap button');
                            var removeFilterButton = $('.admin__current-filters-list .action-remove');

                            removeFilterButton.on('click', function () {
                                var id = $(this).attr('data-id');
                                var selector = '[name*=' + id +']'

                                $('input' + selector).val('');
                                $('select' + selector + ' option:selected').prop("selected", false)
                                getGrid().doFilter();
                            });

                            $('.admin__current-filters-actions-wrap .action-clear').on('click', function () {
                                getGrid().resetFilter()
                            })

                            filterButton.on('click', function () {
                                if (filterButton.hasClass('_active')) {
                                    return close();
                                }

                                return open();
                            });

                            function open() {
                                filterButton.addClass('_active');
                                filterBlock.addClass('_show');
                            }

                            function close() {
                                filterButton.removeClass('_active');
                                filterBlock.removeClass('_show');
                            }

                        });
                    </script>
                <?php endif; ?>

                <div class="admin__data-grid-header-row <?php /* @noEscape */ echo $massActionAvailable ? '_massaction' : '';?>">
                    <?php if ($massActionAvailable): ?>
                        <?php /* @noEscape */ echo $block->getMassactionBlockHtml() ?>
                    <?php endif; ?>
                    <?php $countRecords = $block->getCollection()->getSize(); ?>
                    <div class="admin__control-support-text">
                        <span id="<?php /* @noEscape */ echo $block->escapeHtml($block->getHtmlId()) ?>-total-count" <?php /* @noEscape */ echo $block->getUiId('total-count') ?>>
                            <?php /* @noEscape */ echo $countRecords ?>
                        </span>
                        <?php /* @noEscape */ echo __('records found') ?>
                        <span id="<?php /* @noEscape */ echo $block->escapeHtml($block->getHtmlId()) ?>_massaction-count"
                              class="mass-select-info _empty"><strong data-role="counter">0</strong> <span><?php /* @noEscape */ echo __('selected') ?></span></span>
                    </div>

                    <?php if ($block->getPagerVisibility()): ?>
                        <div class="admin__data-grid-pager-wrap">
                            <select name="<?php /* @noEscape */ echo $block->getVarNameLimit() ?>"
                                    id="<?php /* @noEscape */ echo $block->escapeHTML($block->getHtmlId())?>_page-limit"
                                    onchange="<?php /* @noEscape */ echo $block->getJsObjectName() ?>.loadByElement(this)"
                                    class="admin__control-select">
                                <option value="20"<?php if ($block->getCollection()->getPageSize() == 20): ?>
                                    selected="selected"<?php endif; ?>>20
                                </option>
                                <option value="30"<?php if ($block->getCollection()->getPageSize() == 30): ?>
                                    selected="selected"<?php endif; ?>>30
                                </option>
                                <option value="50"<?php if ($block->getCollection()->getPageSize() == 50): ?>
                                    selected="selected"<?php endif; ?>>50
                                </option>
                                <option value="100"<?php if ($block->getCollection()->getPageSize() == 100): ?>
                                    selected="selected"<?php endif; ?>>100
                                </option>
                                <option value="200"<?php if ($block->getCollection()->getPageSize() == 200): ?>
                                    selected="selected"<?php endif; ?>>200
                                </option>

                                <?php if ($block->isAllowedCustomPageSize()): ?>
                                    <option value="500"<?php if ($block->getCollection()->getPageSize() == 500): ?>
                                        selected="selected"<?php endif; ?>>500
                                    </option>
                                    <option value="1000"<?php if ($block->getCollection()->getPageSize() == 1000): ?>
                                        selected="selected"<?php endif; ?>>1000
                                    </option>
                                    <option value="2000"<?php if ($block->getCollection()->getPageSize() == 2000): ?>
                                        selected="selected"<?php endif; ?>>2000
                                    </option>
                                <?php endif; ?>
                            </select>
                            <label for="<?php /* @noEscape */ echo $block->escapeHTML($block->getHtmlId())?><?php /* @noEscape */ echo $block->escapeHTML($block->getHtmlId())?>_page-limit"
                                   class="admin__control-support-text"><?php /* @noEscape */ echo __('per page') ?></label>

                            <div class="admin__data-grid-pager">
                                <?php $_curPage = $block->getCollection()->getCurPage() ?>
                                <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>
                                <?php if ($_curPage > 1): ?>
                                    <button class="action-previous"
                                            type="button"
                                            onclick="<?php /* @noEscape */ echo $block->getJsObjectName() ?>.setPage('<?php /* @noEscape */ echo($_curPage - 1) ?>');return false;">
                                        <span><?php /* @noEscape */ echo __('Previous page') ?></span>
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="action-previous disabled"><span><?php /* @noEscape */ echo __('Previous page') ?></span></button>
                                <?php endif; ?>
                                <input type="text"
                                       id="<?php /* @noEscape */ echo $block->escapeHTML($block->getHtmlId())?>_page-current"
                                       name="<?php /* @noEscape */ echo $block->getVarNamePage() ?>"
                                       value="<?php /* @noEscape */ echo $_curPage ?>"
                                       class="admin__control-text"
                                       onkeypress="<?php /* @noEscape */ echo $block->getJsObjectName() ?>.inputPage(event, '<?php /* @noEscape */ echo $_lastPage ?>')" <?php /* @noEscape */ echo $block->getUiId('current-page') ?> />
                                <label class="admin__control-support-text" for="<?php /* @noEscape */ echo $block->escapeHTML($block->getHtmlId())?>_page-current">
                                    <?php /* @noEscape */ echo __('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>') ?>
                                </label>
                                <?php if ($_curPage < $_lastPage): ?>
                                    <button type="button"
                                            title="<?php /* @noEscape */ echo __('Next page') ?>"
                                            class="action-next"
                                            onclick="<?php /* @noEscape */ echo $block->getJsObjectName() ?>.setPage('<?php /* @noEscape */ echo($_curPage + 1) ?>');return false;">
                                        <span><?php /* @noEscape */ echo __('Next page') ?></span>
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="action-next disabled"><span><?php /* @noEscape */ echo __('Next page') ?></span></button>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
            <table class="data-grid" id="<?php /* @noEscape */ echo $block->escapeHtml($block->getId()) ?>_table">
                <?php
                /* This part is commented to remove all <col> tags from the code. */
                /* foreach ($block->getColumns() as $_column): ?>
                <col <?php echo $_column->getHtmlProperty() ?> />
                <?php endforeach; */
                ?>
                <?php if ($block->getHeadersVisibility() || $block->getFilterVisibility()): ?>
                    <thead>
                    <?php if ($block->getHeadersVisibility()): ?>
                        <tr>
                            <?php foreach ($block->getColumns() as $_column): ?>
                                <?php if ($_column->getHeaderHtml() == '&nbsp;'):?>
                                    <th class="data-grid-th" data-column="<?php /* @noEscape */ echo $_column->getId() ?>"
                                        <?php /* @noEscape */ echo $_column->getHeaderHtmlProperty() ?>>&nbsp;</th>
                                <?php else: ?>
                                    <?php /* @noEscape */ echo $_column->getHeaderHtml()?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                    <?php if ($block->getFilterVisibility()): ?>
                        <tr class="data-grid-filters" data-role="filter-form">
                            <?php foreach ($block->getColumns() as $_column): ?>
                                <td data-column="<?php /* @noEscape */ echo $_column->getId() ?>" <?php /* @noEscape */ echo $_column->getHeaderHtmlProperty() ?>>
                                    <?php /* @noEscape */ echo $_column->getFilterHtml() ?>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif ?>
                    </thead>
                <?php endif; ?>
                <?php if ($block->getCountTotals()): ?>
                    <tfoot>
                    <tr class="totals">
                        <?php foreach ($block->getColumns() as $_column): ?>
                            <th class="<?php /* @noEscape */ echo $_column->getCssProperty() ?>">
                                <?php /* @noEscape */ echo($_column->hasTotalsLabel()) ? $_column->getTotalsLabel() : $_column->getRowField($_column->getGrid()->getTotals()) ?>
                            </th>
                        <?php endforeach; ?>
                    </tr>
                    </tfoot>
                <?php endif; ?>

                <tbody>
                <?php if (($block->getCollection()->getSize() > 0) && (!$block->getIsCollapsed())): ?>
                    <?php foreach ($block->getCollection() as $_index => $_item): ?>
                        <tr title="<?php /* @noEscape */ echo $block->getRowUrl($_item) ?>"<?php if ($_class = $block->getRowClass($_item)): ?>
                            class="<?php /* @noEscape */ echo $_class; ?>"<?php endif; ?> >
                            <?php foreach ($block->getColumns() as $_column):
                                if ($block->shouldRenderCell($_item, $_column)):
                                    $_rowspan = $block->getRowspan($_item, $_column);
                                    ?>
                                <td <?php /* @noEscape */ echo($_rowspan ? 'rowspan="' . $_rowspan . '" ' : '') ?>
                                    class="<?php /* @noEscape */ echo $_column->getCssProperty() ?>
                                        <?php /* @noEscape */ echo $_column->getId() == 'massaction' ? 'data-grid-checkbox-cell': ''?>"><?php /* @noEscape */ echo(($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') ?></td><?php
                                        if ($block->shouldRenderEmptyCell($_item, $_column)):
                                            ?>
                                        <td colspan="<?php /* @noEscape */ echo $block->getEmptyCellColspan($_item) ?>"
                                            class="last"><?php /* @noEscape */ echo $block->getEmptyCellLabel() ?></td><?php
                                    endif;
                                endif;
                            endforeach; ?>
                        </tr>
                        <?php if ($_multipleRows = $block->getMultipleRows($_item)): ?>
                            <?php foreach ($_multipleRows as $_i): ?>
                                <tr>
                                    <?php foreach ($block->getMultipleRowColumns($_i) as $_column): ?>
                                        <td class="<?php /* @noEscape */ echo $_column->getCssProperty() ?>
                                        <?php /* @noEscape */ echo $_column->getId() == 'massaction' ? 'data-grid-checkbox-cell': ''?>">
                                            <?php /* @noEscape */ echo(($_html = $_column->getRowField($_i)) != '' ? $_html : '&nbsp;') ?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <?php if ($block->shouldRenderSubTotal($_item)): ?>
                            <tr class="subtotals">
                                <?php foreach ($block->getSubTotalColumns() as $_column): ?>
                                    <td class="<?php /* @noEscape */ echo $_column->getCssProperty() ?>
                                           <?php /* @noEscape */ echo $_column->getId() == 'massaction' ? 'data-grid-checkbox-cell': ''?>">
                                        <?php /* @noEscape */ echo($_column->hasSubtotalsLabel() ? $_column->getSubtotalsLabel() :
                                            $_column->getRowField($block->getSubTotalItem($_item))
                                        );
                                        ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php elseif ($block->getEmptyText()): ?>
                    <tr class="data-grid-tr-no-data">
                        <td class="<?php /* @noEscape */ echo $block->getEmptyTextClass() ?>"
                            colspan="<?php /* @noEscape */ echo $numColumns ?>"><?php /* @noEscape */ echo $block->getEmptyText() ?></td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>

        </div>
        <?php if ($block->canDisplayContainer()): ?>
    </div>
    <script>
        var deps = [];

        <?php if ($block->getDependencyJsObject()): ?>
        deps.push('uiRegistry');
        <?php endif; ?>

        <?php if (strpos($block->getRowClickCallback(), 'order.') !== false): ?>
        deps.push('Magento_Sales/order/create/form')
        <?php endif; ?>

        deps.push('mage/adminhtml/grid');

        <?php if (is_array($block->getRequireJsDependencies())): ?>
        <?php foreach ($block->getRequireJsDependencies() as $dependency): ?>
        deps.push('<?php /* @noEscape */ echo $dependency; ?>');
        <?php endforeach; ?>
        <?php endif; ?>

        require(deps, function(<?php echo ($block->getDependencyJsObject() ? 'registry' : '') ?>){
            //<![CDATA[
            <?php if ($block->getDependencyJsObject()): ?>
            registry.get('<?php /* @noEscape */ echo $block->getDependencyJsObject() ?>', function (<?php /* @noEscape */ echo $block->getDependencyJsObject() ?>) {
                <?php endif; ?>

                <?php /* @noEscape */ echo $block->getJsObjectName() ?> = new varienGrid(<?php /* @noEscape */ echo \Ess\M2ePro\Helper\Json::encode($block->getId()) ?>, '<?php /* @noEscape */ echo $block->getGridUrl() ?>', '<?php /* @noEscape */ echo $block->getVarNamePage() ?>', '<?php /* @noEscape */ echo $block->getVarNameSort() ?>', '<?php /* @noEscape */ echo $block->getVarNameDir() ?>', '<?php /* @noEscape */ echo $block->getVarNameFilter() ?>');
                <?php /* @noEscape */ echo $block->getJsObjectName() ?>.useAjax = '<?php /* @noEscape */ echo $block->getUseAjax() ?>';
                <?php if ($block->getRowClickCallback()): ?>
                <?php /* @noEscape */ echo $block->getJsObjectName() ?>.rowClickCallback = <?php /* @noEscape */ echo $block->getRowClickCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getCheckboxCheckCallback()): ?>
                <?php /* @noEscape */ echo $block->getJsObjectName() ?>.checkboxCheckCallback = <?php /* @noEscape */ echo $block->getCheckboxCheckCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getRowInitCallback()): ?>
                <?php /* @noEscape */ echo $block->getJsObjectName() ?>.initRowCallback = <?php /* @noEscape */ echo $block->getRowInitCallback() ?>;
                <?php /* @noEscape */ echo $block->getJsObjectName() ?>.initGridRows();
                <?php endif; ?>
                <?php if ($block->getMassactionBlock() && $block->getMassactionBlock()->isAvailable()): ?>
                <?php /* @noEscape */ echo $block->getMassactionBlock()->getJavaScript() ?>
                <?php endif ?>
                <?php /* @noEscape */ echo $block->getAdditionalJavaScript(); ?>

                <?php if ($block->getDependencyJsObject()): ?>
            });
            <?php endif; ?>
            //]]>

        });

        //fix magento time picker event loop deadlock
        require(['jquery', 'jquery/jquery-ui-timepicker-addon'], function(jQuery) {

            var base_updateDateTime = jQuery.timepicker.constructor.prototype._updateDateTime;

            jQuery.timepicker.constructor.prototype._updateDateTime = function(dp_inst) {
                var triggerFunc = this.$input.trigger;
                this.$input.trigger = function() {};

                base_updateDateTime.call(this, dp_inst);

                this.$input.trigger = triggerFunc;
            };
        });
    </script>
<?php endif; ?>
<?php endif ?>
