<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Description\Preview $block */

?>

<?php echo $block->createBlock('HelpBlock')->setData([
    'style' => 'margin-top: 30px',
    'no_hide' => true,
    'title' => $block->__('Description Preview'),
    'content' => $block->__('If your description contains M2E Pro Attributes, some of them such as Image URLs, Images, etc. might display for the previewing the value which is different from the actual one that will be sent to eBay.')
])->toHtml() ?>

<div class="pagination_container page-main-actions">
    <div class="product_title">
        <h2><?php echo $block->getData('title'); ?> (ID: <?php echo $block->getData('magento_product_id'); ?>)</h2>
    </div>
</div>

<div class="description_container">
    <?php echo $block->getData('description'); ?>
</div>
