<?php /** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Order\Edit\ShippingAddress $block */ ?>

<table class="order-info form-list">
    <tbody>

    <tr>
        <td class="label"><?php echo $block->__('Name');?></td>
        <td class="value">
            <strong>
                <?php echo $block->getHelper('Data')->escapeHtml($block->getOrder()->getChildObject()->getBuyerName()) ?>
            </strong>
        </td>
    </tr>

    <tr>
        <td class="label"><?php echo $block->__('eBay User ID');?></td>
        <td class="value">
            <strong>
                <?php echo $block->getHelper('Data')->escapeHtml($block->getOrder()->getChildObject()->getBuyerUserId()) ?>
            </strong>
        </td>
    </tr>

    <?php $buyerTaxId = $block->getOrder()->getChildObject()->getBuyerTaxId(); ?>

    <?php if (!empty($buyerTaxId)): ?>

        <tr>
            <td class="label"><?php echo $block->__('Tax ID');?></td>
            <td class="value">
                <strong>
                    <?php echo $block->getHelper('Data')->escapeHtml($buyerTaxId); ?>
                </strong>
            </td>
        </tr>

    <?php endif; ?>

    <tr>
        <td class="label"><?php echo $block->__('Email');?></td>
        <td class="value">
            <strong>
                <?php if ($block->getOrder()->getChildObject()->getBuyerEmail() != '') { ?>
                    <?php if (stripos($block->getOrder()->getChildObject()->getBuyerEmail(), 'Invalid Request') !== false) { ?>
                        &lt;<?php echo $block->__('Private Restriction'); ?>&gt;<br/>
                    <?php } else { ?>
                        &lt;<?php echo $block->getHelper('Data')->escapeHtml($block->getOrder()->getChildObject()->getBuyerEmail()); ?>&gt;<br/>
                    <?php } ?>
                <?php } ?>
            </strong>
        </td>
    </tr>

    <?php if (!$block->getOrder()->getChildObject()->isUseClickAndCollect() && !$block->getOrder()->getChildObject()->isUseInStorePickup()): ?>
        <tr>
            <td class="label"><?php echo $block->__('Address'); ?></td>
            <td class="value">
                <strong>

                    <?php echo $block->getHelper('Data')->escapeHtml($block->getOrder()->getChildObject()->getBuyerName()) ?>

                    <?php if (!empty($block->getShippingAddress())): ?>

                        <?php if (!empty($block->getShippingAddress()['street'][0])): ?>
                            <br/><?php echo $block->getHelper('Data')->escapeHtml($block->getShippingAddress()['street'][0]); ?>
                        <?php endif; ?>

                        <?php if (!empty($block->getShippingAddress()['street'][1])): ?>
                            <br/><?php echo $block->getHelper('Data')->escapeHtml($block->getShippingAddress()['street'][1]); ?>
                        <?php endif; ?>

                        <?php if (!empty($block->getShippingAddress()['city'])): ?>
                            <br/><?php echo $block->getHelper('Data')->escapeHtml(implode(', ', array($block->getShippingAddress()['city'], $block->getShippingAddress()['state'], $block->getShippingAddress()['postal_code']))) ?>
                        <?php endif; ?>

                        <?php if (!empty($block->getShippingAddress()['country_name'])): ?>
                            <br/>
                            <?php
                            if (!empty($block->getShippingAddress()['country_name'])) {
                                echo $block->getHelper('Data')->escapeHtml($block->getShippingAddress()['country_name']);
                            } else {
                                echo $block->getHelper('Data')->escapeHtml($block->getShippingAddress()['country_code']);
                            }
                            ?>
                        <?php endif; ?>

                        <?php if (!empty($block->getShippingAddress()['phone']) && stripos($block->getShippingAddress()['phone'], 'Invalid Request') === false): ?>
                            <br/><?php echo 'T: ' . $block->getHelper('Data')->escapeHtml($block->getShippingAddress()['phone']); ?>
                        <?php endif; ?>

                    <?php endif; ?>

                </strong>
            </td>
        </tr>
    <?php endif; ?>

    </tbody>
</table>
