<?php
/**
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\HelpBlock $block */

?>

<div
    id="<?php /* @noEscape */ echo $block->getHtmlId(); ?>"
    class="block_notices m2epro-box-style
    <?php /* @noEscape */ echo $block->getClass(); ?>
    <?php if ($block->hasNoCollapse()) :
        ?>no_collapse<?php
    endif; ?>
    <?php if ($block->hasTooltiped()) :
        ?>tooltiped<?php
    endif; ?>
    <?php if ($block->hasAlwaysShow()) :
        ?>always_show<?php
    endif; ?>
    "
    <?php if ($block->hasStyle()) :
        ?>style="<?php /* @noEscape */ echo $block->getStyle(); ?>"<?php
    endif; ?>
>
    <div class="bar">
        <?php if (!$block->getTitle() && !$block->hasNoCollapse()) : ?>
            <a class="shrink icon icon-shrink" href="javascript://" onclick="BlockNoticeObj.shrinkContent('<?php /* @noEscape */ echo $block->getHtmlId(); ?>')" title="<?php /* @noEscape */ echo $block->__('Collapse'); ?>"></a>
        <?php endif; ?>
        <?php if (!$block->hasTooltiped() && !$block->hasNoHide()) : ?>
            <a class="icon icon-close" href="javascript://" onclick="BlockNoticeObj.hideBlock('<?php /* @noEscape */ echo $block->getHtmlId(); ?>')" title="<?php /* @noEscape */ echo $block->__('Hide Block'); ?>"></a>
        <?php endif; ?>
    </div>

    <?php if ($block->getTitle()) : ?>
        <div class="title title-expand">
            <a href="javascript://" <?php if (!$block->hasNoCollapse()) :
                ?>onclick="BlockNoticeObj.expandTitledContent('<?php /* @noEscape */ echo $block->getHtmlId(); ?>')"<?php
                                    endif; ?> title="<?php /* @noEscape */ echo $block->__('Collapse'); ?>">
                <?php /* @noEscape */ echo $block->getTitle(); ?>
                <span class="icon icon-expand"></span>
            </a>
        </div>
    <?php else : ?>
        <div class="title expand">
            <a href="javascript://" <?php if (!$block->hasNoCollapse()) :
                ?>onclick="BlockNoticeObj.expandContent('<?php /* @noEscape */ echo $block->getHtmlId(); ?>')"<?php
                                    endif; ?> title="<?php /* @noEscape */ echo $block->__('Expand'); ?>">
                <span class="help"><?php /* @noEscape */ echo $block->__('Help Information'); ?></span>
                <span class="icon icon-expand"></span>
            </a>
        </div>
    <?php endif; ?>

    <div class="content <?php if ($block->getTitle()) :
        ?>titled-content<?php
                        endif; ?>">
        <?php /* @noEscape */ echo $block->getContent(); ?>
    </div>
</div>
