The Module interface is unavailable and the background tasks stop running. Service can be put under maintenance automatically due to the following reasons:<br /><br />

<ul style="margin-left: 30px;">
    <li>
        <p>Module installation failed, e.g. due to the incorrect installation via Magento Component Manager, incompatibility of Magento and its Modules or other related technical issues.</p>
    </li>
    <li>
        <p>Module upgrade failed, e.g. due to the improper M2E Pro tables updating or php %magento2_installation_dir%/bin/magento setup:upgrade command running.</p>
    </li>
</ul>

Please contact <a href="mailto:support@m2epro.com">M2E Pro Support Team</a> to resolve the issue.