<style>

    .form-list tr {
        line-height: 35px;
    }

</style>

<div id="requirements_popup_content" style="display: none;">
    <div class="fieldset-wrapper" id="magento_block_system_requirements_popup">

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('requirements') ?>
            </div>
        </div>

    </div>
</div>