<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\RequirementsPopup $block */

?>

<style>

    .form-list tr {
        line-height: 35px;
    }

</style>

<div id="requirements_popup_content" style="display: none;">
    <div class="fieldset-wrapper" id="magento_block_system_requirements_popup">

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('requirements') ?>
            </div>
        </div>

    </div>
</div>
