<?php /** @var \Ess\M2ePro\Block\Adminhtml\StoreSwitcher $this */ ?>

<?php if ($websites = $this->getWebsites()): ?>

    <select
        id="<?php echo $this->getStoreSelectId(); ?>"
        name="<?php echo $this->getStoreSelectName(); ?>"
        style="width: 250px;"
        class="select admin__control-select <?php echo $this->getClass(); ?> <?php if ($this->isRequiredOption()) : ?> M2ePro-store-switcher-validation<?php endif; ?>"
    >

        <?php if ($this->hasEmptyOption()): ?>
            <option value="-1"></option>
        <?php endif; ?>

        <?php if ($this->hasDefaultOption() && $this->isDisplayDefaultStoreModeUp()): ?>
            <option value="<?php echo $this->getDefaultStoreId(); ?>"<?php if($this->getStoreId() == $this->getDefaultStoreId()): ?> selected="selected"<?php endif; ?>><?php echo $this->getDefaultStoreName(); ?></option>
        <?php endif; ?>

        <?php foreach ($websites as $website): ?>
            <?php $showWebsite=false; ?>
            <?php foreach ($website->getGroups() as $group): ?>
                <?php $showGroup=false; ?>
                <?php foreach ($this->getStores($group) as $store): ?>
                    <?php if ($showWebsite == false): ?>
                        <?php $showWebsite = true; ?>
                        <optgroup label="<?php echo $website->getName(); ?>"></optgroup>
                    <?php endif; ?>
                    <?php if ($showGroup == false): ?>
                        <?php $showGroup = true; ?>
                        <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $group->getName(); ?>">
                    <?php endif; ?>
                    <option value="<?php echo $store->getId(); ?>"<?php if($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $store->getName(); ?></option>
                <?php endforeach; ?>
                <?php if ($showGroup): ?>
                    </optgroup>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>

        <?php if ($this->hasDefaultOption() && $this->isDisplayDefaultStoreModeDown()): ?>
            <option value="<?php echo $this->getDefaultStoreId(); ?>"<?php if($this->getStoreId() == $this->getDefaultStoreId()): ?> selected="selected"<?php endif; ?>><?php echo $this->getDefaultStoreName(); ?></option>
        <?php endif; ?>

    </select>

<?php endif; ?>