<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Category\Chooser $block */

use \Ess\M2ePro\Helper\Component\Ebay\Category as Category;

$categoriesData = $block->getCategoriesData();
$itemSpecificsRequired = isset($categoriesData[Category::TYPE_EBAY_MAIN]['mode']) && $block->isItemSpecificsRequired();

$block->jsPhp->addConstants($block->getHelper('Data')
    ->getClassConstants(\Ess\M2ePro\Model\Ebay\Template\Category::class));
$block->jsPhp->addConstants($block->getHelper('Data')
    ->getClassConstants(\Ess\M2ePro\Helper\Component\Ebay\Category::class));
$block->jsPhp->addConstants($block->getHelper('Data')
    ->getClassConstants(\Ess\M2ePro\Block\Adminhtml\Ebay\Template\Category\Chooser::class));

$block->jsUrl->addUrls($block->getHelper('Data')->getControllerActions('Ebay\Category'));
$block->jsUrl->addUrls($block->getHelper('Data')->getControllerActions('Ebay\Marketplace'));

$block->jsTranslator->addTranslations([
    'Select'                      => $block->__('Select'),
    'Reset'                       => $block->__('Reset'),
    'No recently used Categories' => $block->__('No recently used Categories'),
    'Change Category'             => $block->__('Change Category'),
    'Edit'                        => $block->__('Edit'),
    'Category'                    => $block->__('Category'),
    'Not Selected'                => $block->__('Not Selected'),
    'No results'                  => $block->__('No results'),

    'Category Settings' => $block->__('Category Settings'),
    'Specifics'         => $block->__('Specifics'),
    'eBay Primary Store Category must be selected.' => $block->__('eBay Primary Store Category must be selected.'),

    'Try to refreshEbayCategories.'  => $block->__('Try to <a href="javascript:void(0)" onclick="EbayTemplateCategoryChooserObj.refreshEbayCategories()">update Marketplaces Data</a> and repeat the Search.'),
    'Try to refreshStoreCategories.' => $block->__('Try to <a href="javascript:void(0)" onclick="EbayTemplateCategoryChooserObj.refreshStoreCategories()">refresh eBay Store Data</a> and repeat the Search.'),
]);

$categoryModeJson       = $block->getHelper('Data')->jsonEncode($block->getCategoryMode());
$selectedCategoriesJson = json_encode($categoriesData, JSON_FORCE_OBJECT);
$attributesJson         = $block->getHelper('Data')->jsonEncode($block->getAttributes());
$isEditCategoryAllowed  = (int)$block->getIsEditCategoryAllowed();
$isWizardModeJson       = $block->getHelper('Data')->jsonEncode(!$block->getHelper('View\Ebay')->isInstallationWizardFinished());


$js = "
    window.EbayTemplateCategoryChooserObj = new EbayTemplateCategoryChooser('{$block->getMarketplaceId()}', '{$block->getAccountId()}');

    EbayTemplateCategoryChooserObj.setCategoryMode({$categoryModeJson});
    EbayTemplateCategoryChooserObj.setSelectedCategories({$selectedCategoriesJson});
    EbayTemplateCategoryChooserObj.setAttributes({$attributesJson});
    EbayTemplateCategoryChooserObj.setIsEditCategoryAllowed({$isEditCategoryAllowed});
    EbayTemplateCategoryChooserObj.setIsWizardMode({$isWizardModeJson});
";

$block->js->add("
require([
    'M2ePro/Ebay/Template/Category/Chooser'
], function(){

    {$js}

});
");

?>

<style>
    table.m2e-category-chooser td {
        padding-bottom: 3px;
    }
</style>

<form id="edit_form">

    <?php if ($block->isCategoryModeBoth() || $block->isCategoryModeEbay() || $block->isCategoryModeEbayPrimary() || $block->isCategoryModeEbaySecondary()): ?>
        <div class="entry-edit" id="magento_block_ebay_listing_category_chooser_ebay" style="padding-top: 5px;">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $block->__('eBay Catalog'); ?></h4>
            </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="m2e-category-chooser" cellspacing="0" cellpadding="0" style="margin-left: 26px">

                    <?php if (!$block->isCategoryModeEbaySecondary()) : ?>
                        <tr>
                            <td class="label" style="width: 110px;">
                                <?php echo $block->__('Primary'); ?> <span class="required">*</span>
                            </td>

                            <td class="value" style="min-width: 300px;">
                                <?php echo $block->getCategoryPathHtml(Category::TYPE_EBAY_MAIN) ?>
                                <input type="text" style="display: none" id="category_validation" name="category_validation" class="required-entry" value="<?php if (isset($categoriesData[Category::TYPE_EBAY_MAIN]['value'])) : echo $categoriesData[Category::TYPE_EBAY_MAIN]['value']; endif; ?>" />
                            </td>
                            <?php if ($block->getIsEditCategoryAllowed()) : ?>
                                <td class="value" style="padding-left: 15px;">
                                    <a id="ebay_template_category_chooser_ebay_primary_category_edit"
                                       href="#" style="padding-left: 150px;"
                                       onclick="EbayTemplateCategoryChooserObj.showEditPopUp(<?php echo \Ess\M2ePro\Helper\Component\Ebay\Category::TYPE_EBAY_MAIN; ?>)"><?php echo $block->__('Edit'); ?></a>
                                </td>
                            <?php endif; ?>
                        </tr>
                        <tr>
                            <td class="label" style="width: 110px;">
                                <?php echo $block->__('Item Specifics'); ?>:
                                <?php if ($itemSpecificsRequired): ?>
                                    <span class="required">*</span>
                                <?php endif; ?>
                            </td>

                            <td class="value" style="min-width: 300px;">
                                <?php if (!isset($categoriesData[Category::TYPE_EBAY_MAIN]['is_custom_template'])) : ?>
                                    <?php $color = $itemSpecificsRequired ? 'red' : 'grey'; ?>
                                    <span style="font-style: italic; color: <?php echo $color; ?>"><?php echo $block->__('Not Set'); ?></span>
                                <?php elseif ($categoriesData[Category::TYPE_EBAY_MAIN]['is_custom_template'] == 1) : ?>
                                    <span><?php echo $block->__('Custom'); ?></span>
                                <?php else : ?>
                                    <span><?php echo $block->__('Default'); ?></span>
                                <?php endif; ?>
                                <input type="text" style="display: none" id="specifics_validation" name="specifics_validation" class="<?php if ($itemSpecificsRequired) : echo ' required-entry '; endif; ?>" value="<?php if (isset($categoriesData[Category::TYPE_EBAY_MAIN]['is_custom_template'])) : echo $categoriesData[Category::TYPE_EBAY_MAIN]['is_custom_template']; endif; ?>" />
                            </td>

                            <?php if (isset($categoriesData[Category::TYPE_EBAY_MAIN]['mode']) && $categoriesData[Category::TYPE_EBAY_MAIN]['mode'] != \Ess\M2ePro\Model\Ebay\Template\Category::CATEGORY_MODE_NONE): ?>
                                <td style="float: right" class="value">
                                    <a id="ebay_template_category_chooser_item_specifics_edit" href="#"
                                       onclick="EbayTemplateCategoryChooserObj.editSpecifics()"><?php echo $block->__('Edit'); ?></a>
                                </td>
                            <?php endif; ?>

                            <?php if (isset($categoriesData[Category::TYPE_EBAY_MAIN]['is_custom_template']) && $categoriesData[Category::TYPE_EBAY_MAIN]['is_custom_template']): ?>
                                <td style="float: right" class="value">
                                    <a href="#" style="padding-right: 10px;" onclick="EbayTemplateCategoryChooserObj.resetSpecificsToDefault()"><?php echo $block->__('Reset to Default'); ?></a>
                                </td>
                            <?php endif; ?>
                        </tr>

                    <?php endif; ?>

                    <?php if ($block->isCategoryModeBoth() || $block->isCategoryModeEbay()) : ?>
                        <tr>
                            <td colspan="6" style="padding: 10px 0">
                                <hr style="border: 1px solid silver; border-bottom: none;">
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php if (!$block->isCategoryModeEbayPrimary()) : ?>
                        <tr>
                            <td class="label" style="width: 110px;">
                                <?php echo $block->__('Secondary'); ?>
                            </td>

                            <td class="value" style="min-width: 300px;">
                                <?php echo $block->getCategoryPathHtml(Category::TYPE_EBAY_SECONDARY) ?>
                            </td>
                            <?php if ($block->getIsEditCategoryAllowed()) : ?>
                                <td class="value" style="padding-left: 15px;">
                                    <a href="#" style="padding-left: 150px;" onclick="EbayTemplateCategoryChooserObj.showEditPopUp(<?php echo \Ess\M2ePro\Helper\Component\Ebay\Category::TYPE_EBAY_SECONDARY; ?>)"><?php echo $block->__('Edit'); ?></a>
                                </td>
                            <?php endif; ?>
                        </tr>
                    <?php endif; ?>

                </table>

            </div>
        </div>
    </div>

    <?php endif; ?>

    <?php if ($block->hasStoreCatalog()) : ?>

        <?php if ($block->isCategoryModeBoth() || $block->isCategoryModeStore()) : ?>

            <div class="entry-edit" id="magento_block_ebay_listing_category_chooser_store" style="padding-top: 25px;">

                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $block->__('eBay Store Category'); ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">

                        <table class="m2e-category-chooser" cellspacing="0" cellpadding="0" style="margin-left: 26px">

                            <tr>
                                <td class="label" style="width: 110px;">
                                    <?php echo $block->__('Primary'); ?>
                                </td>

                                <td class="value" style="min-width: 300px;">
                                    <?php echo $block->getCategoryPathHtml(Category::TYPE_STORE_MAIN) ?>
                                    <input type="hidden" class="main_store_category_value" name="main_store_category_value" value="<?php echo isset($categoriesData[Category::TYPE_STORE_MAIN]['value']) ? $categoriesData[Category::TYPE_STORE_MAIN]['value'] : ''; ?>" />
                                </td>
                                <?php if ($block->getIsEditCategoryAllowed()) : ?>
                                    <td class="value" style="padding-left: 15px;">
                                        <a href="#" style="padding-left: 150px;" onclick="EbayTemplateCategoryChooserObj.showEditPopUp(<?php echo \Ess\M2ePro\Helper\Component\Ebay\Category::TYPE_STORE_MAIN; ?>)"><?php echo $block->__('Edit'); ?></a>
                                    </td>
                                <?php endif; ?>
                            </tr>

                            <tr>
                                <td class="label" style="width: 110px;">
                                    <?php echo $block->__('Secondary'); ?>
                                </td>

                                <td class="value" style="min-width: 300px;">
                                    <?php echo $block->getCategoryPathHtml(Category::TYPE_STORE_SECONDARY) ?>
                                    <input type="hidden" id="secondary_store_category_value" class="secondary_store_category_value" value="<?php echo isset($categoriesData[Category::TYPE_STORE_SECONDARY]['value']) ? $categoriesData[Category::TYPE_STORE_SECONDARY]['value'] : ''; ?>" />
                                </td>
                                <?php if ($block->getIsEditCategoryAllowed()) : ?>
                                    <td class="value" style="padding-left: 15px;">
                                        <a href="#" style="padding-left: 150px;" onclick="EbayTemplateCategoryChooserObj.showEditPopUp(<?php echo \Ess\M2ePro\Helper\Component\Ebay\Category::TYPE_STORE_SECONDARY; ?>)"><?php echo $block->__('Edit'); ?></a>
                                    </td>
                                <?php endif; ?>
                            </tr>

                        </table>

                    </div>
                </div>

            </div>

        <?php endif; ?>

    <?php endif; ?>

</form>
