<?php
/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Listing\Preview $this */

$images = $this->getImages();
$variations = $this->getVariations();

?>

<?php echo $this->createBlock('HelpBlock')->setData([
    'title' => $this->__('eBay Item Preview'),
    'content' => $this->__('
        This Page is a <strong>stylized Template</strong> of the prospective eBay Page.<br/><br/>
        The Template displays <strong>eBay Item information</strong> which will be sent on eBay during the List/ Relist/ Revise
        Actions. The information presented on this Page is <strong>not available on eBay</strong> yet. The Template just gives
        you a chance to <strong>Preview</strong> how the Product will be Shown on eBay.<br/><br/>
        You can have a preliminary <strong>Overview</strong> of the Product Title, eBay Category, Item Condition, Quantity,
        Price, all of the available Product Variations and more other.<br/><br/>
        There are tabs under which the main Item Specifics, Description, Shipping, Payment and Return data can be found.
        The available information <strong>does not contain all of the details</strong>, only the Key Points.
    '),
    'no_hide' => true
])->toHtml(); ?>

<div class="pagination_container page-main-actions">
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <?php

                $previousProduct = $this->getProductShortInfo(\Ess\M2ePro\Block\Adminhtml\Ebay\Listing\Preview::PREVIOUS);
                if (!is_null($previousProduct)):
                    ?>
                    <?php
                    echo $this->createBlock('Magento\Button')->setData([
                        'onclick' => "setLocation('{$previousProduct['url']}')",
                        'label' => "{$this->truncate($previousProduct['title'], 30)} (ID: {$previousProduct['id']})",
                        'class' => 'action-default back',
                        'title' => $previousProduct['title']
                    ])->toHtml()
                    ?>
                <?php endif; ?>

                <?php
                $nextProduct = $this->getProductShortInfo(\Ess\M2ePro\Block\Adminhtml\Ebay\Listing\Preview::NEXT);
                if (!is_null($nextProduct)): ?>
                    <?php
                    echo $this->createBlock('Magento\Button')->setData([
                        'onclick' => "setLocation('{$nextProduct['url']}')",
                        'label' => "{$this->truncate($nextProduct['title'], 30)} (ID: {$nextProduct['id']})",
                        'class' => 'action-default forward',
                        'title' => $nextProduct['title']
                    ])->toHtml()
                    ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php $currentProduct = $this->getProductShortInfo(\Ess\M2ePro\Block\Adminhtml\Ebay\Listing\Preview::CURRENT); ?>
    <div class="current_product_title">
        <h2 title="<?php echo $currentProduct['title']; ?>">
            <?php echo "{$this->truncate($currentProduct['title'], 40)} (ID: {$currentProduct['id']})"; ?>
        </h2>
    </div>
</div>

<div class="preview_container">
    <div class="image_container">
        <?php
        $imageGallery = $images['gallery'];

        if (!empty($images['variations'])) {
            foreach($images['variations']['images'] as $variationImage) {
                $imageGallery = array_merge($imageGallery, $variationImage);
            }
        }

        if (empty($imageGallery)) {
            echo "<img id='product_image' src='{$this->getViewFileUrl('Ess_M2ePro::images/preview_no_images.png')}'>";
        } else {
            echo "<img id='product_image' src='{$imageGallery[0]}'>";
            echo '<div class="gallery_container">';

            if (count($imageGallery) > 1) {
                foreach ($imageGallery as $image) {
                    echo "<img src='{$image}' onclick='EbayListingPreviewItemsObj.onClickGalleryImage(this)'>";
                }
            }

            echo '</div>';
        }
        ?>
    </div>

    <div class="info_container">
        <div class="category_breadcrumbs">
            <?php echo $this->getCategory(); ?>
        </div>
        <div class="product_title">
            <?php echo $this->getTitle(); ?>
        </div>
        <div class="product_subtitle">
            <?php echo $this->getSubtitle(); ?>
        </div>

        <hr class="title_separator"/>

        <table class="variation_table">
            <tr>
                <td class="field_title">
                    <?php echo $this->__('Item Condition'); ?>:
                </td>
                <td>
                    <?php echo $this->getCondition(); ?>
                </td>
            </tr>

            <?php
            $conditionNote = $this->getConditionNote();

            if($conditionNote):
            ?>
            <tr>
                <td class="field_title">
                    <?php echo $this->__('Seller Note'); ?>:
                </td>
                <td>
                    <?php echo $conditionNote; ?>
                </td>
            </tr>
            <?php endif; ?>

            <?php
            $qty = $this->getQty();

            if (!empty($variations) && $qty):
                ?>
                <?php foreach ($variations['variation_sets'] as $attribute => $data): ?>
                <tr>
                    <td class='field_title'><?php echo $attribute; ?>:</td>
                    <td>
                        <select class='variation_select admin__control-select' name='<?php echo $this->getHelper('Data')->escapeHtml($attribute, null, ENT_QUOTES); ?>'
                                onchange='EbayListingPreviewItemsObj.onChangeVariationSelect(this)'>
                            <option value="">- <?php echo $this->__('Select'); ?> -</option>
                            <?php foreach ($data as $option): ?>
                                <option value='<?php echo $this->getHelper('Data')->escapeHtml($option, null, ENT_QUOTES); ?>'>
                                    <?php echo $this->getHelper('Data')->escapeHtml($option, null, ENT_QUOTES); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tr>
                <td class="field_title">
                    <?php echo $this->__('Quantity'); ?>:
                </td>
                <td>
                    <?php if($qty): ?>
                    <span id="product_qty">
                        <?php echo $qty; ?>
                    </span> <?php echo $this->__('available'); ?>
                    <?php else: ?>
                        <span id="product_qty">
                            <?php echo $this->__('N/A'); ?>
                        </span>
                    <?php endif; ?>
                </td>
            </tr>
        </table>
    </div>

    <?php

    $currency = "{$this->getCurrency()} {$this->getCurrencySymbol()}";
    $price = $this->getPrice($variations);

    if(!is_null($price['price']) && $qty):

    ?>

    <div class="price_container">
        <table>
            <tr>
                <td>
                    <div id="product_discount_stp" class="price_discount" <?php if (!isset($price['price_stp'])):?>style="display: none"<?php endif;?>>
                        <?php echo $currency; ?><span id='product_price_stp'><?php if (isset($price['price_stp']) && $price['price_stp'] > $price['price']) { echo $price['price_stp']; } ?></span>
                    </div>
                    <div id="product_discount_map" class="price_discount" <?php if (!isset($price['price_map'])):?>style="display: none"<?php endif;?>>
                        <?php echo $currency; ?><span id='product_price_map'><?php if (isset($price['price_map']) && $price['price_map'] > $price['price']) { echo $price['price_map']; } ?></span>
                    </div>
                    <div class='price_currency'>
                        <?php echo $currency; ?><span id='product_price'><?php echo $price['price']; ?></span>
                    </div>
                </td>
                <td class="price_container_td">
                    <button class='buy_it_now' type='button'>
                        <?php echo $this->__('Buy it now'); ?>
                    </button>
                    <br/>
                    <button class='add_to_cart' type='button'>
                        <?php echo $this->__('Add to cart'); ?>
                    </button>
                </td>
            </tr>
        </table>
    </div>

    <?php endif; ?>

    <?php

    $description = $this->getDescription();
    $specifics = $this->getSpecifics();
    $return = $this->getReturnPolicy();
    $otherCategories = $this->getOtherCategories();

    ?>

    <ul class="tabs-horiz">
        <?php if (!empty($specifics)): ?>
        <li data-tab="specifics" onclick="EbayListingPreviewItemsObj.onTabClick(this);">
            <?php echo $this->__('Item Specifics'); ?>
        </li>
        <?php endif; ?>
        <?php if ($description): ?>
        <li data-tab="description" onclick="EbayListingPreviewItemsObj.onTabClick(this);">
            <?php echo $this->__('Description'); ?>
        </li>
        <?php endif; ?>
        <li data-tab="shipping" onclick="EbayListingPreviewItemsObj.onTabClick(this);">
            <?php echo $this->__('Shipping'); ?>
        </li>
        <li data-tab="payment" onclick="EbayListingPreviewItemsObj.onTabClick(this);">
            <?php echo $this->__('Payment'); ?>
        </li>
        <?php if (!empty($return)): ?>
        <li data-tab="return" onclick="EbayListingPreviewItemsObj.onTabClick(this);">
            <?php echo $this->__('Return'); ?>
        </li>
        <?php endif; ?>
        <?php if (!empty($otherCategories)): ?>
        <li data-tab="other" onclick="EbayListingPreviewItemsObj.onTabClick(this);">
            <?php echo $this->__('Other'); ?>
        </li>
        <?php endif; ?>
    </ul>

    <div class="description_container tab_container">
        <?php if ($description): ?>
            <div>
                <?php echo $description; ?>
            </div>
        <?php endif; ?>
    </div>

    <div class="specifics_container tab_container">

        <?php if (!empty($specifics)): ?>
            <table class="field_table field_table_specifics">
                <thead>
                <tr>
                    <td><?php echo $this->__('Name'); ?></td>
                    <td><?php echo $this->__('Value'); ?></td>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($specifics as $specific): ?>
                 <tr>
                     <td><?php echo $specific['name']; ?></td>
                     <td><?php echo implode(', ', $specific['value']); ?></td>
                 </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
    <div class="shipping_container tab_container">
        <div>
            <span class="field_title"><?php echo $this->__('Item Location'); ?>:</span>
            <?php echo $this->getItemLocation(); ?>
        </div>
        <div class="field_group"><?php echo $this->__('Domestic Shipping'); ?></div>
        <div>
            <span class="field_title"><?php echo $this->__('Type'); ?>:</span>
            <?php echo $this->getShippingLocalType(); ?>
        </div>

        <?php
        $shippingLocalServices = $this->getShippingLocalServices();

        if (!empty($shippingLocalServices)):
            ?>

            <div>
                <table class="field_table">
                    <thead>
                    <tr>
                        <td class="field_table_service"><?php echo $this->__('Service'); ?></td>
                        <td class="field_table_cost"><?php echo $this->__('Cost'); ?></td>
                        <?php if(!$this->isLocalShippingCalculated()): ?>
                            <td class="field_table_additional_cost"><?php echo $this->__('Additional Cost'); ?></td>
                        <?php endif; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($shippingLocalServices as $shippingLocalService): ?>
                        <tr>
                            <td><?php echo $shippingLocalService['service']; ?></td>
                            <td>
                                <?php
                                if (isset($shippingLocalService['cost'])) {
                                    if ($shippingLocalService['cost'] == 0) {
                                        echo $this->__('Free');
                                    } else {
                                        echo $currency . $shippingLocalService['cost'];
                                    }
                                }
                                if (isset($shippingLocalService['is_free'])) {
                                    if ($shippingLocalService['is_free']) {
                                        echo $this->__('Free');
                                    } else {
                                        echo $this->__('Calculated');
                                    }
                                }
                                ?>
                            </td>
                        <?php if(!$this->isLocalShippingCalculated()): ?>
                            <td>
                                <?php
                                if (isset($shippingLocalService['cost_additional'])) {
                                    if ($shippingLocalService['cost_additional'] == 0) {
                                        echo $this->__('Free');
                                    } else {
                                        echo $currency . $shippingLocalService['cost_additional'];
                                    }
                                }
                                ?>
                            </td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>

        <?php
        $dispatchTime = $this->getShippingDispatchTime();

        if (!is_null($dispatchTime)):
            ?>
            <div>
                <span class="field_title"><?php echo $this->__('Dispatch Time'); ?>:</span>
                <?php echo $dispatchTime; ?>
            </div>
        <?php endif; ?>

        <?php

        $shippingLocalHandlingCost = $this->getShippingLocalHandlingCost();

        if ($shippingLocalHandlingCost):
            ?>
            <div>
                <span class="field_title"><?php echo $this->__('Handling Cost'); ?>:</span>
                <?php echo $currency . $shippingLocalHandlingCost; ?>
            </div>
        <?php endif; ?>

        <?php

        $shippingInternationalType = $this->getShippingInternationalType();

        if ($shippingInternationalType): ?>

            <div class="field_group"><?php echo $this->__('International Shipping'); ?></div>

            <?php if ($this->getShippingInternationalGlobalOffer()): ?>
            <div>
                <span class="field_title">
                    <?php echo $this->__('Offer Global Shipping Program'); ?>:
                </span>
                <?php echo $this->__('Yes'); ?>
            </div>
            <?php endif; ?>

            <div>
                <span class="field_title"><?php echo $this->__('Type'); ?>:</span>
                <?php echo $shippingInternationalType ?>
            </div>

            <?php

            $shippingInternationalServices = $this->getShippingInternationalServices();

            if (!empty($shippingInternationalServices)):

                ?>
                <div>
                    <table class="field_table">
                        <thead>
                        <tr>
                            <td class="field_table_service"><?php echo $this->__('Service'); ?></td>
                            <td class="field_table_cost"><?php echo $this->__('Cost'); ?></td>
                            <?php if(!$this->isInternationalShippingCalculated()): ?>
                                <td class="field_table_additional_cost"><?php echo $this->__('Additional Cost'); ?></td>
                            <?php endif; ?>
                            <td class="field_table_locations"><?php echo $this->__('Locations'); ?></td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($shippingInternationalServices as $shippingInternationalService): ?>
                            <tr>
                                <td>
                                    <?php
                                    if($shippingInternationalService['service']){
                                        echo $shippingInternationalService['service'];
                                    } else {
                                        echo $this->__('Buyer Should Contact Seller');
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    if (isset($shippingInternationalService['cost'])) {
                                        if ($shippingInternationalService['cost'] == 0) {
                                            echo $this->__('Free');
                                        } else {
                                            echo $currency . $shippingInternationalService['cost'];
                                        }
                                    } else {
                                        echo $this->__('Calculated');
                                    }

                                    ?>
                                </td>
                                <?php if(!$this->isInternationalShippingCalculated()): ?>
                                    <td>
                                        <?php
                                        if (isset($shippingInternationalService['cost_additional'])) {
                                            if ($shippingInternationalService['cost_additional'] == 0) {
                                                echo $this->__('Free');
                                            } else {
                                                echo $currency . $shippingInternationalService['cost_additional'];
                                            }
                                        }
                                        ?>
                                    </td>
                                <?php endif; ?>
                                    <td><?php echo $shippingInternationalService['locations']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php

        $shippingInternationalHandlingCost = $this->getShippingInternationalHandlingCost();

        if ($shippingInternationalHandlingCost):
            ?>
            <div>
                <span class="field_title"><?php echo $this->__('Handling Cost'); ?>:</span>
                <?php echo $currency . $shippingInternationalHandlingCost; ?>
            </div>
        <?php endif; ?>

        <?php

        $excludedLocations = $this->getShippingExcludedLocations();

        if ($excludedLocations):
            ?>

            <div class="field_group"><?php echo $this->__('Excluded Locations'); ?></div>

            <div>
                <span class="field_title"><?php echo $this->__('Locations'); ?>:</span>
                <?php echo $excludedLocations; ?>
            </div>
        <?php endif; ?>
    </div>

    <div class="payment_container tab_container">
        <?php
        $payment = $this->getPayment();

        if (isset($payment['paypal'])) {
            echo "<img src='{$this->getViewFileUrl('Ess_M2ePro::images/img_echeck.png')}'>";
        }
        ?>

        <?php if (!empty($payment['paymentMethods'])): ?>
            <table>
                <tr>
                    <td class="field_title"><?php echo $this->__('Payment Methods'); ?>:&nbsp;</td>
                    <td>
                        <?php foreach ($payment['paymentMethods'] as $paymentMethod): ?>
                            <div><?php echo $paymentMethod; ?></div>
                        <?php endforeach; ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    </div>
    <div class="return_container tab_container">
        <?php if (!empty($return)): ?>
            <?php if ($return['returns_accepted']): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Return Policy'); ?>:</span>
                <?php echo $return['returns_accepted']; ?>
            </div>
            <?php endif; ?>
            <?php if ($return['refund']): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Refund Will Be Given As'); ?>:</span>
                <?php echo $return['refund']; ?>
            </div>
            <?php endif; ?>
            <?php if ($return['returns_within']): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Item Must Be Returned Within'); ?>:</span>
                <?php echo $return['returns_within']; ?>
            </div>
            <?php endif; ?>
            <?php if($return['is_holiday_enabled']): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Extended Holiday Returns'); ?>:</span>
                <?php echo $this->__('Yes'); ?>
            </div>
            <?php endif; ?>
            <?php if ($return['shipping_cost_paid_by']): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Return Shipping Will Be Paid By'); ?>:</span>
                <?php echo $return['shipping_cost_paid_by']; ?>
            </div>
            <?php endif; ?>
            <?php if ($return['restocking_fee_value']): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Restocking Fee Value'); ?>:</span>
                <?php echo $return['restocking_fee_value']; ?>
            </div>
            <?php endif; ?>
            <?php if($return['description']): ?>
                <div>
                    <span class="field_title"><?php echo $this->__('Refund Description'); ?>:</span>
                    <?php echo $return['description']; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div class="other_container tab_container">
        <?php if (isset($otherCategories['secondary'])): ?>
            <div class="field_group"><?php echo $this->__('eBay Catalog'); ?></div>
            <div>
                <span class="field_title"><?php echo $this->__('Secondary Category'); ?>:</span>
                <span class="category_breadcrumbs_black">
                    <?php echo $otherCategories['secondary']; ?>
                </span>
            </div>
        <?php endif; ?>
        <?php if (isset($otherCategories['primary_store']) || isset($otherCategories['secondary_store'])): ?>
            <div class="field_group"><?php echo $this->__('Store Catalog'); ?></div>
        <?php endif; ?>
        <?php if (isset($otherCategories['primary_store'])): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Primary Category'); ?>:</span>
                <span class="category_breadcrumbs_black">
                    <?php echo $otherCategories['primary_store']; ?>
                </span>
            </div>
        <?php endif; ?>
        <?php if (isset($otherCategories['secondary_store'])): ?>
            <div>
                <span class="field_title"><?php echo $this->__('Secondary Category'); ?>:</span>
                <span class="category_breadcrumbs_black">
                    <?php echo $otherCategories['secondary_store']; ?>
                </span>
            </div>
        <?php endif; ?>
    </div>
</div>