<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Listing\View\Settings\Category\Chooser\Wrapper $block */

?>

<div id="chooser_main_container" style="margin-top: 30px;">
    <?php echo $block->getChildHtml('chooser'); ?>
</div>

<div style="clear: both"></div>
