<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Listing\View\Settings\Motors\View\Group\Filters $block */

?>

<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
    <table class="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th"><?php echo $block->__('Filter')?></th>
            <th class="data-grid-th" style="width: 20px;">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getFilters() as $item) { ?>
            <tr>
                <td>
                    <?php echo $item['title']?>
                </td>
                <td>
                    <a title="<?php echo $block->__('Remove') ?>"
                       href="javascript:void(0)"
                       class="ebay-listing-view-icon ebay-listing-view-remove"
                       onclick="EbayListingViewSettingsMotorsAddGroupGridObj.removeFilterFromGroup(this, <?php echo $item['id']?>, <?php echo $block->getGroupId() ?>)">
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
