<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var \Ess\M2ePro\Block\Adminhtml\Wizard\MigrationFromMagento1\Installation\Congratulation\Content $block */

?>

<div class="wizard_block">

    <p>
        <?php echo $block->__('Our congratulations! You have successfully migrated M2E Pro data from Magento v1.x to Magento v2.x.'); ?>
    </p>

    <p>
        <?php echo $block->__('The maintenance mode is disabled and the automatic synchronization is resumed. M2E Pro is now ready to use in Magento v2.x environment.'); ?>
    </p>
</div>