<?php

/** @var \Ess\M2ePro\Block\Adminhtml\Amazon\Mapping\Tabs\AttributeMapping $block */
    echo $block->createBlock('HelpBlock')->setData([
        'content' => __('On this page, the attribute mapping demonstrates the connection between your
         Product Type specifics and the corresponding Magento Product attributes. This mapping guarantees that the
         correct attributes are consistently associated with each Product Type specific. You can edit the saved mapping
         if a different Magento attribute value is more appropriate for a certain Amazon Product Type specific.'),
    ])->toHtml();

    ?>

<form method="post" novalidate="novalidate" enctype="multipart/form-data">
<?php if (count($block->getMappedAttributes()) > 0) : ?>
<table class="data-grid">
    <thead>
        <tr>
            <th class="data-grid-th"><?= /* @noEscape */ __('Product Type Attribute') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */ __('Magento Attribute') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($block->getMappedAttributes() as $mappedAttribute) : ?>
        <tr>
            <td><?= /* @noEscape */ $mappedAttribute->getProductTypeAttributeName() ?></td>
            <td><?= /* @noEscape */ $block->makeMagentoAttributesDropDownHtml($mappedAttribute) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else : ?>
<div style="text-align: center">
    <p><?= /* @noEscape */ $block->getEmptyMappingsText() ?></p>
</div>
<?php endif; ?>
</form>
