<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $block \Ess\M2ePro\Block\Adminhtml\Listing\View\Header */

?>

<style type="text/css">

    div.listing-view-header {
        margin-bottom: 30px !important;
        padding: 10px 15px !important;
    }

    div.listing-view-header span.label {
        font-weight: bold;
    }

    div.listing-view-header span.value {
        color: #8e9393;
    }

    div.listing-view-header ul {
        text-align: justify;
        line-height: 0;
        font-size: 1px;
    }

    div.listing-view-header ul:after {
        width: 100%;
        height: 0;
        visibility: hidden;
        overflow: hidden;
        content: '';
        display: inline-block;
    }

    div.listing-view-header ul li {
        display: inline-block;
        text-align: left;
        line-height: normal;
        font-size: 12px;
        vertical-align: top;
    }

</style>

<div class="m2epro-box-style listing-view-header">
    <ul>
        <?php if (!$block->isListingViewMode()) : ?>
        <li>
            <label>
                <span class="label">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->__('Listing')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->getProfileTitle()); ?>
                </span>
            </label>
        </li>
        <?php endif; ?>
        <li>
            <label>
                <span class="label">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->__('Account')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->getAccountTitle()); ?>
                </span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->__('Marketplace')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->getMarketplaceTitle()); ?>
                </span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->__('Magento Store View')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $block->getHelper('Data')->escapeHtml($block->getStoreViewBreadcrumb(false)); ?>
                </span>
            </label>
        </li>
    </ul>
</div>
