<?php
    /** @var \Ess\M2ePro\Block\Adminhtml\Ebay\Template\Switcher $this */

    $translation = $this->getHelper('Module\Tranlsation');
?>

<div class="template-switcher-container">

    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td class="template-header" style="width: <?php echo $this->getHeaderWidth() ?>px;">
                    <h3 style="margin: 0;"><?php echo $this->getHeaderText() ?></h3>
                </td>

                <?php $display = $this->canDisplaySwitcher() ? '' : 'none'; ?>
                <td class="template-switcher-td" style="display: <?php echo $display ?>;">
                    <select name="<?php echo $this->getSwitcherName() ?>" id="<?php echo $this->getSwitcherId() ?>" data-bind="value: change" class="template-switcher M2ePro-validate-ebay-template-switcher">
                        <?php if ($this->canDisplayUseDefaultOption() && $this->isTemplateModeParentForced()): ?>
                            <option value="<?php echo base64_encode(json_encode(array('mode' => null))) ?>" selected="selected" class="template-switcher-empty-option empty"></option>
                        <?php endif; ?>

                        <?php
                        $value = base64_encode(json_encode(array(
                            'id' => $this->isTemplateModeCustom() ? $this->getTemplateId() : null,
                            'mode' => \Ess\M2ePro\Model\Ebay\Template\Manager::MODE_CUSTOM,
                            'nick' => $this->getTemplateNick()
                        )));
                        $selected = $this->isTemplateModeCustom();
                        ?>
                        <option value="<?php echo $value ?>" <?php if ($selected): ?>selected="selected"<?php endif; ?> class="template-switcher-custom-option">
                            <?php echo $translation->__('Custom Settings') ?>
                        </option>

                        <?php if ($this->canDisplayUseDefaultOption()): ?>
                            <?php
                            $value = base64_encode(json_encode(array(
                                'id' => null,
                                'mode' => \Ess\M2ePro\Model\Ebay\Template\Manager::MODE_PARENT,
                                'nick' => $this->getTemplateNick()
                            )));
                            $selected = $this->isTemplateModeParent() && !$this->isTemplateModeParentForced();
                            ?>
                            <option value="<?php echo $value; ?>" <?php if ($selected): ?>selected="selected"<?php endif; ?> class="template-switcher-parent-option">
                                <?php echo $translation->__('Use From Listing Settings') ?>
                            </option>
                        <?php endif; ?>

                        <?php $templates = $this->getTemplates(); ?>

                        <?php if (count($templates) > 0): ?>
                            <optgroup label="<?php echo $this->getHelper('Data')->escapeHtml($translation->__('Policies')) ?>" class="templates-group">
                                <?php foreach ($templates as $template): ?>
                                    <?php
                                    $value = base64_encode(json_encode(array(
                                        'id' => $template->getId(),
                                        'mode' => \Ess\M2ePro\Model\Ebay\Template\Manager::MODE_TEMPLATE,
                                        'nick' => $this->getTemplateNick()
                                    )));
                                    $selected = $this->isTemplateModeTemplate() && $this->getTemplateId() == $template->getId();
                                    ?>
                                    <option value="<?php echo $value; ?>" <?php if ($selected): ?>selected="selected"<?php endif; ?> class="template-switcher-template-option">
                                        <?php echo $this->getHelper('Data')->escapeHtml($template->getTitle()) ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        <?php endif; ?>
                    </select>
                </td>

                <?php if ($this->getHelper('View\Ebay')->isSimpleMode() && $this->isTemplateModeTemplate()): ?>

                    <td class="template-title-td">
                        <span class="template-title"><?php echo $this->getHelper('Data')->escapeHtml($this->getTemplateObject()->getTitle()) ?></span>
                    </td>

                <?php endif; ?>

                <td style="padding-left: 10px; width: 100%;" class="template-nick-td">

                    <div id="template_<?php echo $this->getTemplateNick() ?>_nick_label" style="display: none;">
                        <img src="<?php echo $this->getSkinUrl('M2ePro/images/note_cell_bg.gif'); ?>" />
                        <span class="template" style="display: none;"><?php echo $translation->__('Policy') ?></span>
                        <?php if ($this->isTemplateModeParentForced()): ?>
                            <span class="parent" style="display: none;"><?php echo $translation->__('Please, specify a value suitable for all chosen Products.') ?></span>
                        <?php endif; ?>
                    </div>

                    <div id="template_<?php echo $this->getTemplateNick() ?>_edit" style="display: none;">
                        <a href="javascript: void(0);" onclick="EbayListingTemplateSwitcherHandlerObj.editTemplate('<?php echo $this->getTemplateNick() ?>');"><?php echo $translation->__('View') ?>&nbsp;/&nbsp;<?php echo $translation->__('Edit') ?></a>
                        <?php echo $translation->__('or') ?>
                        <a href="javascript: void(0);" onclick="EbayListingTemplateSwitcherHandlerObj.customizeTemplate('<?php echo $this->getTemplateNick() ?>');"><?php echo $translation->__('Use Custom Settings') ?></a>
                    </div>

                </td>
            </tr>
            <tr>
                <td></td>
                <td id="template_switcher_<?php echo $this->getTemplateNick() ?>_messages" colspan="2" class="value" style="padding-left: 30px;"></td>
            </tr>
        </table>
    </div>

</div>