<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $block \Ess\M2ePro\Block\Adminhtml\Amazon\Template\ShippingOverride\Edit\Form */

$block->css->add("
    #shipping_override_rule_table span.required {
        display: inline;
    }
");
?>

<div class="entry-edit form-inline">
    <?php echo $block->getFormHtml();?>
</div>
<?php echo $block->getChildHtml('form_after');?>

<table id="shipping_override_rule_table" class="data-grid data-grid-not-hovered" style="display: none" cellpadding="0" cellspacing="0">
    <thead>
    <tr class="headings">
        <th class="data-grid-th" style="width: 20%"><?php echo $block->__('Service') ?><span class="required"> *</span></th>
        <th class="data-grid-th" style="width: 21%"><?php echo $block->__('Locale') ?><span class="required"> *</span></th>
        <th class="data-grid-th" style="width: 15%"><?php echo $block->__('Override Method') ?><span class="required"> *</span></th>
        <th class="data-grid-th" style="width: 14%"><?php echo $block->__('Mode') ?><span class="required"> *</span></th>
        <th class="data-grid-th" style="width: 13%"><?php echo $block->__('Cost') ?><span class="required"> *</span></th>
        <th class="data-grid-th" style="width: 7%"><?php echo $block->__('Currency') ?></th>
        <th class="data-grid-th type-butt last" style="width: 10%;">&nbsp;</th>
    </tr>
    </thead>
    <tbody id="shipping_override_rules_table_tbody">
    <!-- #shipping_override_rule_table_row_template inserts here -->
    </tbody>
    <tfoot>
    <tr>
        <td colspan="7" style="text-align: right"><?php echo $block->getChildHtml('add_shipping_override_rule_button') ?></td>
    </tr>
    </tfoot>
</table>

<table id="shipping_override_rule_table_row_template" style="display: none;">
    <tbody>
    <tr id="shipping_override_rule_%i%_tr" class="shipping-override-rule">
        <td>
            <select name="shipping_override_rule[service][%i%]" class="required-entry shipping-override-service" onchange="AmazonTemplateShippingOverrideObj.ruleServiceChange(this)"></select>
        </td>
        <td>
            <select name="shipping_override_rule[location][%i%]" class="required-entry shipping-override-location" disabled="disabled" style="display: none" onchange="AmazonTemplateShippingOverrideObj.ruleLocationChange(this)"></select>
            <input name="shipping_override_rule[option][%i%]" type="hidden" class="shipping-override-option"/>
        </td>
        <td>
            <select name="shipping_override_rule[type][%i%]" class="required-entry shipping-override-type" disabled="disabled" style="display: none" onchange="AmazonTemplateShippingOverrideObj.ruleTypeChange(this)">
                <option value="" class="empty"></option>
                <option value="<?php echo \Ess\M2ePro\Model\Amazon\Template\ShippingOverride\Service::TYPE_EXCLUSIVE ?>"><?php echo $block->__('Exclusive'); ?></option>
                <option value="<?php echo \Ess\M2ePro\Model\Amazon\Template\ShippingOverride\Service::TYPE_ADDITIVE ?>"><?php echo $block->__('Additive'); ?></option>
                <option value="<?php echo \Ess\M2ePro\Model\Amazon\Template\ShippingOverride\Service::TYPE_RESTRICTIVE ?>"><?php echo $block->__('Restrictive'); ?></option>
            </select>
        </td>
        <td>
            <select name="shipping_override_rule[cost_mode][%i%]" class="required-entry shipping-override-cost-mode" disabled="disabled" style="display: none" onchange="AmazonTemplateShippingOverrideObj.ruleCostModeChange(this)">
                <option value="" class="empty"></option>
                <option value="<?php echo \Ess\M2ePro\Model\Amazon\Template\ShippingOverride\Service::COST_MODE_FREE ?>"><?php echo $block->__('Free'); ?></option>
                <option value="<?php echo \Ess\M2ePro\Model\Amazon\Template\ShippingOverride\Service::COST_MODE_CUSTOM_VALUE ?>"><?php echo $block->__('Custom Value'); ?></option>
                <option value="<?php echo \Ess\M2ePro\Model\Amazon\Template\ShippingOverride\Service::COST_MODE_CUSTOM_ATTRIBUTE ?>"><?php echo $block->__('Custom Attribute'); ?></option>
            </select>
        </td>
        <td>
            <input name="shipping_override_rule[cost_value][%i%]" type="text" class="required-entry input-text M2ePro-validation-float shipping-override-cost-custom-value" disabled="disabled" style="display: none; text-align: right"/>
            <select name="shipping_override_rule[cost_value][%i%]" class="required-entry shipping-override-cost-custom-attribute" disabled="disabled" style="display: none;">
                <option value="" class="empty"></option>
                <?php foreach ($block->getAttributes() as $attribute) { ?>
                    <option value="<?php echo $attribute['code'] ?>"><?php echo $block->getHelper('Data')->escapeHtml($attribute['label']); ?></option>
                <?php } ?>
            </select>
        </td>
        <td>
                <span class="shipping-override-rule-currency" style="line-height: 33px;">
                    <?php if (!empty($block->formData['marketplace_id'])) { ?>
                        <?php echo $block->getHelper('Data')->escapeHtml($block->getActiveRecordFactory()->getCachedObjectLoaded('Marketplace', $block->formData['marketplace_id'])->getChildObject()->getCurrency()) ?>
                    <?php } ?>
                </span>
        </td>
        <td>
            <?php echo $block->getChildHtml('remove_shipping_override_rule_button'); ?>
        </td>
    </tr>
    </tbody>
</table>
