<?php
/** @var $block \Ess\M2ePro\Block\Adminhtml\Amazon\Listing\Product\Search\Menu */
?>
<div id="productSearchMenu_pop_up_content">
    <div class="hor-scroll" style="padding-top: 15px; margin-bottom: 0">

        <?php echo $block->getWarnings(); ?>

        <div style="text-align:center; margin: 20px auto;">
            <div>
                <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.showSearchManualPrompt();"><?php echo $block->__('Assign ASIN/ISBN Manually'); ?></a>
                <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo $block->__('Search ASIN/ISBN by data that will be specified on the next step.'); ?></div>
            </div>
            <div>
                <?php if (!$block->isIndividualFromBundleOrSimpleOrDownloadable()) { ?>

                    <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.showSearchGeneralIdAutoPrompt();">
                        <?php echo $block->__('Assign ASIN/ISBN Automatically'); ?>
                    </a>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo $block->__('Search ASIN/ISBN by data that have already been specified in Listing Search Settings.'); ?></div>

                <?php } else { ?>
                    <span style="color:#666; font-size:140%"><?php echo $block->__('Assign ASIN/ISBN Automatically'); ?></span>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;">
                        <?php echo $block->__('This Option is not available for Simple with Custom Options, Bundle and Downloadable with Separated Links Magento Products. Please use "Assign ASIN/ISBN Manually" functionality.'); ?>
                    </div>
                <?php } ?>
            </div>

            <div>
                <?php if (!$block->isIndividualFromBundleOrSimpleOrDownloadable() &&
                          !$block->isParentFromBundleOrSimpleOrDownloadable()) { ?>

                    <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.addNewGeneralId();">
                        <?php echo $block->__('Assign Settings for New ASIN/ISBN'); ?>
                    </a>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo $block->__('Define Settings for New Amazon Product Creation. ASIN/ISBN will be assigned by Amazon.'); ?></div>

                <?php } else { ?>
                    <span style="color:#666; font-size:140%"><?php echo $block->__('Assign Settings for New ASIN/ISBN'); ?></span>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;">
                        <?php echo $block->__('This Option is not available for Simple with Custom Options, Bundle and Downloadable with Separated Links Magento Products.'); ?>
                    </div>
                <?php } ?>
            </div>

        </div>

    </div>
</div>